const ACTIVITY_TYPES=['Kreativband','Club','Besonderes Angebot'];let activityType='Kreativband',activitySelected=null,activitySearch='',activityTeam='alle';
function ensureCreativeRooms(){Store.creativeRooms.forEach(r=>{if(!Store.activities.some(a=>a.id===r.id))Store.activities.push({id:r.id,type:'Kreativband',year:State.year,name:r.name,icon:r.icon,licenses:r.licenses,lebEnabled:true});});Store.save();}
function activities(){ensureCreativeRooms();const offers=Store.activities.filter(a=>a.type===activityType&&(a.type==='Kreativband'||a.year===State.year)).sort((a,b)=>a.name.localeCompare(b.name,'de'));let content=header('Angebote');content+=`<div class="toolbar formgrid"><div><label>Jahrgang</label><select onchange="State.year=Number(this.value);activitySelected=null;render()">${[5,6,7].map(y=>`<option value="${y}" ${State.year===y?'selected':''}>Jahrgang ${y}</option>`).join('')}</select></div><div><label>Bereich</label><select onchange="activityType=this.value;activitySelected=null;render()">${ACTIVITY_TYPES.map(t=>`<option ${activityType===t?'selected':''}>${t}</option>`).join('')}</select></div></div>`;if(activityType!=='Kreativband'&&canEdit())content+=`<button class="chip dark" onclick="openActivityEditor()">+ ${activityType} anlegen</button>`;content+=activitySelected?renderActivityDetail(activitySelected):`<div class="offerGrid">${offers.map(a=>`<div class="tile activityTile" onclick="activitySelected='${a.id}';render()"><span class="activityIcon">${a.icon||activityIcon(a.type)}</span><b>${esc(a.name)}</b><span>${activityType==='Kreativband'?'Besuche mit einem Klick erfassen':activityMemberCount(a.id)+' Teilnehmende'}</span></div>`).join('')||'<div class="card empty">Noch keine Einträge.</div>'}</div>`;shell(content);}
function activityIcon(type){return type==='Kreativband'?'🎨':type==='Club'?'🏆':'✨';}function activityMemberCount(id){return Object.values(Store.activityRecords).filter(r=>r.activityId===id&&r.active).length;}
function renderActivityDetail(id){const a=Store.activities.find(x=>x.id===id);if(!a)return'';let pupils=Store.pupils.filter(p=>String(p.className).startsWith(String(State.year))).filter(p=>activityTeam==='alle'||p.team===activityTeam).filter(p=>!activitySearch||(p.first+' '+p.last+' '+p.short).toLowerCase().includes(activitySearch.toLowerCase())).sort((x,y)=>x.last.localeCompare(y.last,'de'));return`<button class="chip" onclick="activitySelected=null;render()">← Übersicht</button>${a.type!=='Kreativband'&&canEdit()?`<button class="chip" onclick="openActivityEditor('${a.id}')">Bearbeiten</button>`:''}<div class="card focusCard"><div><h2>${a.icon||activityIcon(a.type)} ${esc(a.name)}</h2><p>${a.type==='Kreativband'?'Tippe bei anwesenden Kindern auf +1.':esc(a.type)}</p></div><div class="scoreHint">${activityMemberCount(a.id)}<br><span class="mini">Kinder mit Eintrag</span></div></div><div class="toolbar formgrid"><div><label>Team</label><select onchange="activityTeam=this.value;render()"><option value="alle">alle Teams</option>${TEAMS.map(t=>`<option ${activityTeam===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Suche</label><input value="${esc(activitySearch)}" oninput="activitySearch=this.value;render()" placeholder="Name suchen …"></div></div><div class="quickList">${pupils.map(p=>activityQuickRow(a,p)).join('')}</div>`;}
function activityQuickRow(a,p){const key=a.id+'|'+p.id,r=Store.activityRecords[key]||{activityId:a.id,pupilId:p.id,active:false,count:0,note:'',licenses:[]};return`<div class="quickRow"><div><b>${esc(p.short)}</b><div class="mini">${esc(p.team)} · ${esc(p.className)}</div></div><div class="quickActions">${a.type==='Kreativband'?`<strong>${r.count||0}</strong><button class="visitBtn" onclick="addVisit('${a.id}','${p.id}',1)">+1</button><button class="miniBtn" onclick="addVisit('${a.id}','${p.id}',-1)">−</button><button class="miniBtn" onclick="openQualification('${a.id}','${p.id}')">🏅</button>`:`<button class="memberBtn ${r.active?'selected':''}" onclick="toggleMember('${a.id}','${p.id}')">${r.active?'✓ dabei':'+ hinzufügen'}</button>`}<button class="miniBtn" onclick="editActivityNote('${a.id}','${p.id}')">📝</button></div>${r.licenses?.length?`<div class="licenseLine">${r.licenses.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div>`:''}${r.note?`<div class="mini noteLine">${esc(r.note)}</div>`:''}</div>`;}
function addVisit(a,p,delta){const k=a+'|'+p,r=Store.activityRecords[k]||{activityId:a,pupilId:p,active:true,count:0,note:'',licenses:[]};r.active=true;r.count=Math.max(0,(r.count||0)+delta);Store.activityRecords[k]=r;Store.save();render();}
function toggleMember(a,p){const k=a+'|'+p,r=Store.activityRecords[k]||{activityId:a,pupilId:p,active:false,count:0,note:'',licenses:[]};r.active=!r.active;Store.activityRecords[k]=r;Store.save();render();}
function editActivityNote(a,p){const k=a+'|'+p,r=Store.activityRecords[k]||{activityId:a,pupilId:p,active:true,count:0,note:'',licenses:[]};const v=prompt('Notiz:',r.note||'');if(v===null)return;r.note=v.trim();r.active=true;Store.activityRecords[k]=r;Store.save();render();}
function openQualification(a,p){const act=Store.activities.find(x=>x.id===a),k=a+'|'+p,r=Store.activityRecords[k]||{activityId:a,pupilId:p,active:true,count:0,note:'',licenses:[]};const choices=(act.licenses||[]).map((x,i)=>`${i+1}: ${x}${r.licenses?.includes(x)?' ✓':''}`).join('\n');const answer=prompt(`Qualifikation auswählen:\n${choices}\n\nNummer eingeben`, '');const idx=Number(answer)-1;if(idx<0||idx>=act.licenses.length)return;r.licenses=r.licenses||[];const q=act.licenses[idx];r.licenses.includes(q)?r.licenses=r.licenses.filter(x=>x!==q):r.licenses.push(q);r.active=true;Store.activityRecords[k]=r;Store.save();render();}
function openActivityEditor(id=null){State.dialog={mode:'activity',id};renderDialog();}
function renderActivityDialog(target){const a=State.dialog.id?Store.activities.find(x=>x.id===State.dialog.id):{id:null,type:activityType,name:'',year:State.year,period:'',lebEnabled:true};target.innerHTML=`<div class="dialogBackdrop"><div class="dialog"><div class="dialogHead"><h2>${a.id?'Bearbeiten':'Anlegen'}</h2><button class="iconBtn" onclick="State.dialog=null;renderDialog()">×</button></div><label>Name</label><input id="a_name" value="${esc(a.name||'')}"><label>Zeitraum optional</label><input id="a_period" value="${esc(a.period||'')}"><button class="chip dark" onclick="saveActivityDialog()">Speichern</button></div></div>`;}
function saveActivityDialog(){const existing=State.dialog.id?Store.activities.find(x=>x.id===State.dialog.id):null,obj=existing||{id:uid('activity'),type:activityType,year:State.year,lebEnabled:true};obj.name=document.getElementById('a_name').value.trim();obj.period=document.getElementById('a_period').value.trim();if(!obj.name)return;if(!existing)Store.activities.push(obj);Store.save();activitySelected=obj.id;State.dialog=null;render();}
function pupilActivities(pupilId){return Object.values(Store.activityRecords).filter(r=>r.pupilId===pupilId&&r.active).map(r=>({record:r,activity:Store.activities.find(a=>a.id===r.activityId)})).filter(x=>x.activity);}
