let adminFilter={section:'users',subject:'alle',sprint:'alle'};let cloudUserCreateOpen=false;let cloudUserPreset=null;let cloudInitialPassword='';
const KOMPASS_COLLEGIUM_PRESETS=[
  {name:'Mustafa Kavak',gradeAccess:{5:'leitung'},coachTeams:{5:'Blau'}},
  {name:'Betül Copuro',gradeAccess:{5:'teacher'},coachTeams:{5:'Blau'}},
  {name:'Nina Kreuzberger',gradeAccess:{5:'teacher'},coachTeams:{5:'Rot'}},
  {name:'Natalie Brümmer',gradeAccess:{5:'leitung'},coachTeams:{5:'Rot'}},
  {name:'Susanne Judeich',gradeAccess:{5:'teacher'},coachTeams:{5:'Gelb'}},
  {name:'Charlotte Groß',gradeAccess:{5:'teacher'},coachTeams:{}},
  {name:'Moritz Stephan',gradeAccess:{5:'teacher',7:'teacher'},coachTeams:{5:'Violett',7:'Violett'}},
  {name:'Marie Lang',gradeAccess:{5:'teacher'},coachTeams:{5:'Violett'}},
  {name:'Michael Kindl',gradeAccess:{5:'teacher'},coachTeams:{5:'Grün'}},
  {name:'Claudia Rock',gradeAccess:{6:'teacher'},coachTeams:{6:'Blau'}},
  {name:'Nicole Oursin',gradeAccess:{6:'teacher'},coachTeams:{6:'Blau'}},
  {name:'Marcel Moser',gradeAccess:{6:'teacher'},coachTeams:{6:'Rot'}},
  {name:'Dagmar Zwilling',gradeAccess:{6:'teacher'},coachTeams:{6:'Rot'}},
  {name:'Ribanna Tsehaye',gradeAccess:{6:'teacher'},coachTeams:{6:'Gelb'}},
  {name:'Julia Bachmair',gradeAccess:{6:'teacher'},coachTeams:{6:'Gelb'}},
  {name:'Peter Brusda-Gleichmann',gradeAccess:{6:'teacher'},coachTeams:{6:'Violett'}},
  {name:'Juliane Schöne',gradeAccess:{6:'leitung'},coachTeams:{6:'Violett'}},
  {name:'Melanie Schnepf',gradeAccess:{6:'teacher'},coachTeams:{6:'Grün'}},
  {name:'Jörg Vogt',gradeAccess:{6:'teacher'},coachTeams:{6:'Grün'}},
  {name:'Elke Gärtner',gradeAccess:{7:'teacher'},coachTeams:{7:'Blau'}},
  {name:'Karin Beißwenger',gradeAccess:{7:'teacher'},coachTeams:{7:'Blau'}},
  {name:'Katja Kindermann',gradeAccess:{7:'teacher'},coachTeams:{7:'Rot'}},
  {name:'Friedrich Mück',gradeAccess:{7:'teacher'},coachTeams:{7:'Rot'}},
  {name:'Anja Peschel',gradeAccess:{7:'teacher'},coachTeams:{7:'Gelb'}},
  {name:'Michael Feil',gradeAccess:{7:'teacher'},coachTeams:{7:'Gelb'}},
  {name:'Yulia Okhrimenko',gradeAccess:{7:'teacher'},coachTeams:{7:'Violett'}},
  {name:'Marco Dierolf',gradeAccess:{7:'teacher'},coachTeams:{7:'Grün'}},
  {name:'Sabrina Putz',gradeAccess:{7:'teacher'},coachTeams:{7:'Grün'}},
  {name:'Andreas Dinger',gradeAccess:{},coachTeams:{}},
  {name:'Claudia May',gradeAccess:{},coachTeams:{}},
  {name:'Hannah Seitz',gradeAccess:{},coachTeams:{}},
  {name:'Heike von Vietinghoff',gradeAccess:{},coachTeams:{}},
  {name:'Manuela Kümmerer',gradeAccess:{},coachTeams:{}}
];
function staffKey(v){return String(v||'').trim().toLocaleLowerCase('de-DE').replace(/\s+/g,' ');}
function staffEmail(name){return String(name||'').trim().toLocaleLowerCase('de-DE').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'.').replace(/^\.|\.$/g,'')+'@jbgms-sha.de';}
function setCloudInitialPassword(v){cloudInitialPassword=String(v||'');}
function openCloudPreset(name){cloudUserPreset=KOMPASS_COLLEGIUM_PRESETS.find(x=>x.name===name)||{name,gradeAccess:{},coachTeams:{}};cloudUserCreateOpen=true;render();}

function admin(){ if(!canEdit()){shell(header('Kein Zugriff','Nur Stufenleitung und Admin können Kompetenzen bearbeiten.'));return;} let content=header('Kompetenzverwaltung','Werkstatt und Kernfächer sauber verwalten – ohne Browser-Popups.'); content+=`<div class="toolbar"><button class="chip ${adminFilter.section==='users'?'dark':''}" onclick="adminFilter.section='users';render()">Benutzer</button><button class="chip ${adminFilter.section==='workshop'?'dark':''}" onclick="adminFilter.section='workshop';render()">Werkstatt</button><button class="chip ${adminFilter.section==='core'?'dark':''}" onclick="adminFilter.section='core';render()">Kernfächer</button><button class="chip ${adminFilter.section==='sprints'?'dark':''}" onclick="adminFilter.section='sprints';render()">Sprints</button></div>`; if(adminFilter.section==='users')content+=renderUserAdmin(); else if(adminFilter.section==='sprints')content+=renderSprintAdmin(); else content+=renderCompetencyAdmin(adminFilter.section); shell(content); if(adminFilter.section==='users'&&Auth.session?.mode==='cloud')setTimeout(()=>loadCloudUsers(),0); }
function adminTeamsForGrade(grade){const teams=[...new Set((Store.pupils||[]).filter(p=>Number(p.year||String(p.className||'').charAt(0))===Number(grade)).map(p=>p.team).filter(Boolean))];return (teams.length?teams:TEAMS).sort((a,b)=>String(a).localeCompare(String(b),'de'));}
function adminTeamOptions(grade,value=''){return `<option value="" ${!value?'selected':''}>kein eigenes Coach-Team</option>${adminTeamsForGrade(grade).map(t=>`<option value="${esc(t)}" ${value===t?'selected':''}>${esc(t)}</option>`).join('')}`;}
function renderCloudCreateForm(){const p=cloudUserPreset||{name:'',gradeAccess:{},coachTeams:{}};return `<div class="card"><h2>${p.name?'Konto für '+esc(p.name):'Neues Kollegiumskonto'}</h2><p class="mini">Name, bekannte Stufe und Coach-Team sind bereits vorausgefüllt. Du ergänzt nur noch E-Mail und Startpasswort und kannst die Zuordnung bei Bedarf ändern.</p><div class="formgrid"><div><label>Name</label><input id="cu_name" value="${esc(p.name||'')}" placeholder="z. B. Marie Muster"></div><div><label>E-Mail</label><input id="cu_email" type="email" value="${esc(p.name?staffEmail(p.name):'')}" placeholder="vorname.nachname@jbgms-sha.de"></div><div><label>Startpasswort</label><input id="cu_password" type="password" value="${esc(cloudInitialPassword)}" autocomplete="new-password"></div><div><label>Rolle</label><select id="cu_role" onchange="document.getElementById('cu_grades').style.display=this.value==='admin'?'none':''"><option value="teacher">Lehrkraft / Lerncoach</option><option value="admin">Admin</option></select></div></div><div id="cu_grades"><div class="section">Stufenzugriff & Coach-Team</div><div class="formgrid">${[5,6,7].map(g=>`<div><label>Stufe ${g}</label><select id="cu_grade_${g}"><option value="" ${!p.gradeAccess?.[g]?'selected':''}>kein Zugriff</option><option value="teacher" ${p.gradeAccess?.[g]==='teacher'?'selected':''}>Lehrkraft / Lerncoach</option><option value="leitung" ${p.gradeAccess?.[g]==='leitung'?'selected':''}>Stufenleitung</option></select><label class="mini">eigene Lerngruppe</label><select id="cu_team_${g}">${adminTeamOptions(g,p.coachTeams?.[g]||p.coachTeams?.[String(g)]||'')}</select></div>`).join('')}</div></div><button class="chip dark" onclick="createCloudUserFromForm()">Konto anlegen</button><button class="chip" onclick="cloudUserCreateOpen=false;cloudUserPreset=null;render()">Abbrechen</button><div id="cu_error" class="loginError"></div></div>`;}
function renderUserAdmin(){
  if(!Auth.isAdmin())return '<div class="card">Nur Admins können Benutzerkonten verwalten.</div>';
  if(Auth.session?.mode==='cloud')return `<div class="grid2"><div><div class="card"><h2>Kollegiumskonten</h2><p>Konten werden hier zentral angelegt. Stufenrecht und eigene Lerngruppe sind direkt zugeordnet.</p><label>Gemeinsames Erstpasswort für neue Kollegiumskonten</label><input type="password" value="${esc(cloudInitialPassword)}" oninput="setCloudInitialPassword(this.value)" autocomplete="new-password" placeholder="einmal festlegen – wird nicht gespeichert"><p class="mini">Die Schul-E-Mail wird automatisch aus dem Namen gebildet (vorname.nachname@jbgms-sha.de). Das Erstpasswort bleibt nur für diese geöffnete KOMPASS-Sitzung im Speicher.</p><button class="chip dark" onclick="cloudUserPreset=null;cloudUserCreateOpen=!cloudUserCreateOpen;render()">+ Konto anlegen</button><button class="chip" onclick="loadCloudUsers()">Konten neu laden</button><div id="cloudUsers"><p class="mini">Konten werden geladen …</p></div></div>${cloudUserCreateOpen?renderCloudCreateForm():''}</div><div class="card"><h2>Cloud-Speicherung aktiv</h2><p>Schülerdaten, Kalender, Bewertungen und Stundenplanung werden zentral synchronisiert.</p><div class="mini">${esc(Auth.cloud?.url||'')}</div></div></div>`;
  const users=Auth.localUsers();return `<div class="grid2"><div class="card"><h2>Lokale Benutzer</h2><p class="mini">Diese Konten funktionieren nur auf diesem Browser.</p><button class="chip dark" onclick="openUserEditor()">+ Konto anlegen</button><div class="list">${users.map(u=>`<div class="row"><div><b>${esc(u.name)}</b><div class="mini">${esc(u.username)} · ${u.role==='admin'?'Admin':u.role==='leitung'?'Stufenleitung':'Lehrkraft'} · ${u.active!==false?'aktiv':'deaktiviert'}</div></div><button class="chip" onclick="openUserEditor('${u.id}')">Bearbeiten</button></div>`).join('')}</div></div><div class="card"><h2>Was wird gespeichert?</h2><p>Alle KOMPASS-Daten bleiben lokal erhalten. Zusätzlich protokolliert KOMPASS Änderungen automatisch mit Benutzer und Zeitpunkt.</p></div></div>`;
}
async function createCloudUserFromForm(){const err=document.getElementById('cu_error');try{const name=document.getElementById('cu_name').value.trim(),email=document.getElementById('cu_email').value.trim().toLowerCase(),password=document.getElementById('cu_password').value,role=document.getElementById('cu_role').value;const gradeAccess={},coachTeams={};if(role!=='admin')[5,6,7].forEach(g=>{const v=document.getElementById('cu_grade_'+g).value,t=document.getElementById('cu_team_'+g).value;if(v)gradeAccess[g]=v;if(v&&t)coachTeams[g]=t;});if(!name||!email||!password)throw new Error('Bitte Name, E-Mail und Startpasswort eintragen.');if(role!=='admin'&&!Object.keys(gradeAccess).length)throw new Error('Bitte mindestens eine Stufe zuweisen.');await Sync.createCloudUser({name,email,password,role,gradeAccess,coachTeams});cloudUserCreateOpen=false;cloudUserPreset=null;toast('Konto angelegt');render();}catch(e){if(err)err.textContent=e.message||String(e);else alert(e.message||e)}}
function openUserEditor(id=null){State.dialog={mode:'user',id};renderDialog()}
function renderUserDialog(target){const u=State.dialog.id?Auth.localUsers().find(x=>x.id===State.dialog.id):{name:'',username:'',role:'teacher',active:true};target.innerHTML=`<div class="dialogBackdrop"><div class="dialog"><div class="dialogHead"><h2>${State.dialog.id?'Konto bearbeiten':'Konto anlegen'}</h2><button class="iconBtn" onclick="State.dialog=null;renderDialog()">×</button></div><label>Name</label><input id="u_name" value="${esc(u.name)}"><label>Benutzername</label><input id="u_username" value="${esc(u.username)}" ${State.dialog.id?'disabled':''}><label>Rolle</label><select id="u_role"><option value="teacher" ${u.role==='teacher'?'selected':''}>Lehrkraft</option><option value="leitung" ${u.role==='leitung'?'selected':''}>Stufenleitung</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select>${State.dialog.id?`<label class="check"><input id="u_active" type="checkbox" ${u.active!==false?'checked':''}> Konto aktiv</label><label>Neues Passwort (optional)</label><input id="u_password" type="password">`:`<label>Startpasswort</label><input id="u_password" type="password">`}<button class="chip dark" onclick="saveUserDialog()">Speichern</button></div></div>`}
async function saveUserDialog(){try{const name=document.getElementById('u_name').value.trim(),username=document.getElementById('u_username').value.trim(),role=document.getElementById('u_role').value,password=document.getElementById('u_password').value;if(!name||!username){alert('Bitte Name und Benutzername eintragen.');return}if(State.dialog.id){Auth.updateLocalUser(State.dialog.id,{name,role,active:document.getElementById('u_active').checked});if(password)await Auth.resetLocalPassword(State.dialog.id,password)}else{if(!password){alert('Bitte ein Startpasswort vergeben.');return}await Auth.createLocalUser({name,username,password,role})}State.dialog=null;toast('Benutzer gespeichert');render()}catch(e){alert(e.message||e)}}
function cloudAccessSelect(u,grade){const v=u.gradeAccess?.[grade]||'',team=u.coach_teams?.[grade]||u.coach_teams?.[String(grade)]||'';return `<div><label class="mini">Stufe ${grade}</label><select onchange="cloudUserGrade('${u.id}',${grade},this.value)"><option value="" ${!v?'selected':''}>kein Zugriff</option><option value="teacher" ${v==='teacher'?'selected':''}>Lehrkraft / Lerncoach</option><option value="leitung" ${v==='leitung'?'selected':''}>Stufenleitung</option></select><label class="mini">eigene Lerngruppe</label><select onchange="cloudUserCoachTeam('${u.id}',${grade},this.value)">${adminTeamOptions(grade,team)}</select></div>`;}
async function loadCloudUsers(){const box=document.getElementById('cloudUsers');if(!box)return;try{const users=await Sync.cloudProfiles();const existing=new Set(users.map(u=>staffKey(u.display_name)));const missing=KOMPASS_COLLEGIUM_PRESETS.filter(p=>!existing.has(staffKey(p.name)));const missingHtml=missing.length?`<div class="section">Noch kein Konto</div><div class="list">${missing.map(p=>{const access=Object.entries(p.gradeAccess||{}).map(([g,l])=>`Stufe ${g}${l==='leitung'?' · Stufenleitung':''}`).join(' · ')||'Stufenzugriff noch festlegen';const teams=Object.entries(p.coachTeams||{}).map(([g,t])=>`${t}`).join(', ');return `<div class="row"><div><b>${esc(p.name)}</b><div class="mini">${esc(access)}${teams?' · '+esc(teams):''} · kein Login</div></div><button class="chip dark" onclick="openCloudPreset('${String(p.name).replace(/'/g,"\\'")}')">Konto anlegen</button></div>`}).join('')}</div>`:'';const accountsHtml=users.length?`<div class="section">Angelegte Konten</div>${users.map(u=>`<div class="card"><div class="row"><div><b>${esc(u.display_name||'ohne Name')}</b><div class="mini">${u.role==='admin'?'Admin':'Kollegium'} · ${u.active?'aktiv':'gesperrt'}</div></div><div><select onchange="cloudUserRole('${u.id}',this.value)"><option value="teacher" ${u.role==='teacher'?'selected':''}>Kollegium</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select><button class="chip" onclick="cloudUserActive('${u.id}',${!u.active})">${u.active?'Sperren':'Freigeben'}</button></div></div>${u.role==='admin'?'<p class="mini">Admins haben schulweiten Zugriff auf Stufe 5–7.</p>':`<div class="formgrid">${[5,6,7].map(g=>cloudAccessSelect(u,g)).join('')}</div>`}</div>`).join('')}`:'';box.innerHTML=missingHtml+accountsHtml||'<p class="mini">Keine Konten.</p>';}catch(e){box.innerHTML=`<p class="loginError">${esc(e.message||e)}</p>`}}
async function cloudUserRole(id,role){await Sync.updateCloudProfile(id,{role});toast('Rolle gespeichert');loadCloudUsers()}
async function cloudUserActive(id,active){await Sync.updateCloudProfile(id,{active});toast(active?'Konto freigegeben':'Konto gesperrt');loadCloudUsers()}
async function cloudUserGrade(id,grade,level){await Sync.updateCloudGradeAccess(id,grade,level||null);if(!level)await cloudUserCoachTeam(id,grade,'',false);toast('Stufenrecht gespeichert')}
async function cloudUserCoachTeam(id,grade,team,reload=true){const users=await Sync.cloudProfiles(),u=users.find(x=>x.id===id);if(!u)return;const coachTeams={...(u.coach_teams||{})};if(team)coachTeams[String(grade)]=team;else delete coachTeams[String(grade)];await Sync.updateCloudProfile(id,{coach_teams:coachTeams});if(reload){toast('Lerngruppe gespeichert');loadCloudUsers();}}
function renderSprintAdmin(){return `<div class="toolbar"><label>Jahrgang</label><select onchange="State.year=Number(this.value);render()">${visibleYears().map(y=>`<option value="${y}" ${State.year===y?'selected':''}>Jahrgang ${y}</option>`).join('')}</select></div><div class="grid">${Store.sprints.filter(s=>s.year===State.year).sort((a,b)=>a.number-b.number).map(s=>`<div class="card"><h2>Sprint ${s.number}</h2><p>${esc(s.name)}</p><div class="mini">${s.startDate||'kein Start'} – ${s.endDate||'kein Ende'}</div><button class="chip dark" onclick="openSprintEditor('${s.id}')">Bearbeiten</button></div>`).join('')}</div>`;}
function openSprintEditor(id){State.dialog={mode:'sprint',id};renderDialog();}
function renderSprintDialog(target){const s=Store.sprints.find(x=>x.id===State.dialog.id); target.innerHTML=`<div class="dialogBackdrop"><div class="dialog"><div class="dialogHead"><h2>Sprint ${s.number} bearbeiten</h2><button class="iconBtn" onclick="State.dialog=null;renderDialog()">×</button></div><label>Name</label><input id="s_name" value="${esc(s.name)}"><div class="formgrid"><div><label>Startdatum</label><input id="s_start" type="date" value="${esc(s.startDate)}"></div><div><label>Enddatum</label><input id="s_end" type="date" value="${esc(s.endDate)}"></div></div><button class="chip dark" onclick="saveSprintDialog()">Speichern</button></div></div>`;}
function saveSprintDialog(){const s=Store.sprints.find(x=>x.id===State.dialog.id); s.name=document.getElementById('s_name').value.trim(); s.startDate=document.getElementById('s_start').value; s.endDate=document.getElementById('s_end').value; Store.save(); State.dialog=null; toast(); render();}
function renderCompetencyAdmin(section){ const subjects=section==='core'?CORE_SUBJECTS:Store.subjects; if(adminFilter.subject==='alle')adminFilter.subject=subjects[0]||'alle'; const type=section==='core'?'core':'workshop'; const comps=Store.competencies.filter(c=>c.year===State.year&&c.type===type&&(adminFilter.subject==='alle'||c.subject===adminFilter.subject)&&(type==='core'||adminFilter.sprint==='alle'||c.sprint===Number(adminFilter.sprint))).sort((a,b)=>(a.subject+a.category).localeCompare(b.subject+b.category,'de')||(a.order||0)-(b.order||0)); return `<div class="toolbar formgrid"><div><label>Jahrgang</label><select onchange="State.year=Number(this.value);render()">${visibleYears().map(y=>`<option value="${y}" ${State.year===y?'selected':''}>Jahrgang ${y}</option>`).join('')}</select></div><div><label>Fach</label><select onchange="adminFilter.subject=this.value;render()">${subjects.map(s=>`<option ${adminFilter.subject===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div>${type==='workshop'?`<div><label>Sprint</label><select onchange="adminFilter.sprint=this.value;render()"><option value="alle">alle</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${adminFilter.sprint==n?'selected':''}>Sprint ${n}</option>`).join('')}</select></div>`:''}</div><button class="chip dark" onclick="openCompetencyEditor(null,'${type}')">+ Kompetenz anlegen</button><div class="list">${comps.map(c=>`<div class="row"><div><b>${esc(c.text)}</b><div class="mini">${esc(c.subject)} · ${esc(c.category)} ${c.sprint?'· Sprint '+c.sprint:''} · Niveau ${esc(c.level)}${c.maxPoints?' · '+c.maxPoints+' P.':''}</div></div><button class="chip" onclick="openCompetencyEditor('${c.id}','${type}')">Bearbeiten</button></div>`).join('')||'<div class="card empty">Noch keine Kompetenzen.</div>'}</div>`;}
function openCompetencyEditor(id,type){State.dialog={mode:'competency',id,type};renderDialog();}
function renderCompetencyDialog(target){const type=State.dialog.type; const subjects=type==='core'?CORE_SUBJECTS:Store.subjects; const c=State.dialog.id?Store.competencies.find(x=>x.id===State.dialog.id):{id:null,type,year:State.year,sprint:type==='workshop'?State.sprint:null,subject:subjects[0],category:'',area:'',level:'G/M/E',text:'',includeInLeb:true,order:100,maxPoints:null,scoreConfig:{...Store.settings.scoreConfig},note:''}; target.innerHTML=`<div class="dialogBackdrop"><div class="dialog"><div class="dialogHead"><h2>${c.id?'Kompetenz bearbeiten':'Kompetenz anlegen'}</h2><button class="iconBtn" onclick="State.dialog=null;renderDialog()">×</button></div><div class="formgrid"><div><label>Fach</label><select id="c_subject">${subjects.map(s=>`<option ${c.subject===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div>${type==='workshop'?`<div><label>Sprint</label><select id="c_sprint">${[1,2,3,4,5].map(n=>`<option value="${n}" ${c.sprint===n?'selected':''}>Sprint ${n}</option>`).join('')}</select></div>`:''}<div><label>Kategorie</label><input id="c_category" value="${esc(c.category)}" placeholder="z. B. Wortschatz"></div><div><label>Zielniveau</label><select id="c_level"><option ${c.level==='G/M/E'?'selected':''}>G/M/E</option><option ${c.level==='G'?'selected':''}>G</option><option ${c.level==='M'?'selected':''}>M</option><option ${c.level==='E'?'selected':''}>E</option></select></div></div><label>Kompetenztext</label><textarea id="c_text">${esc(c.text)}</textarea><div class="formgrid"><div><label>Maximalpunkte optional</label><input id="c_max" type="number" step="0.5" value="${c.maxPoints??''}"></div><div><label>Reihenfolge</label><input id="c_order" type="number" value="${c.order??100}"></div><div><label>Rot bis %</label><input id="c_red" type="number" value="${c.scoreConfig?.redMax??24}"></div><div><label>Gelb bis %</label><input id="c_yellow" type="number" value="${c.scoreConfig?.yellowMax??74}"></div></div><label>Bemerkung</label><textarea id="c_note">${esc(c.note||'')}</textarea><label class="check"><input id="c_leb" type="checkbox" ${c.includeInLeb?'checked':''}> im LEB berücksichtigen</label><button class="chip dark" onclick="saveCompetencyDialog()">Speichern</button>${c.id?`<button class="chip" onclick="deleteCompetencyDialog()">Löschen</button>`:''}</div></div>`;}
function saveCompetencyDialog(){ const existing=State.dialog.id?Store.competencies.find(x=>x.id===State.dialog.id):null; const type=State.dialog.type; const obj=existing||{id:uid('comp'),type,year:State.year}; obj.subject=document.getElementById('c_subject').value; obj.sprint=type==='workshop'?Number(document.getElementById('c_sprint').value):null; obj.category=document.getElementById('c_category').value.trim()||'Allgemein'; obj.area=obj.category; obj.level=document.getElementById('c_level').value; obj.text=document.getElementById('c_text').value.trim(); obj.maxPoints=document.getElementById('c_max').value===''?null:Number(document.getElementById('c_max').value); obj.order=Number(document.getElementById('c_order').value||100); obj.scoreConfig={redMax:Number(document.getElementById('c_red').value||24),yellowMax:Number(document.getElementById('c_yellow').value||74)}; obj.note=document.getElementById('c_note').value.trim(); obj.includeInLeb=document.getElementById('c_leb').checked; if(!obj.text){alert('Bitte Kompetenztext eintragen.');return;} if(!existing)Store.competencies.push(obj); Store.save(); State.dialog=null; toast(); render();}
function deleteCompetencyDialog(){ if(!confirm('Kompetenz wirklich löschen? Bestehende Bewertungen bleiben als Datensätze erhalten, werden aber nicht mehr angezeigt.'))return; Store.competencies=Store.competencies.filter(c=>c.id!==State.dialog.id); Store.save(); State.dialog=null; toast('Gelöscht'); render();}
