const State={view:'dashboard',year:6,sprint:1,subject:'Englisch',competency:null,pupil:null,search:'',team:'alle',teacher:'',role:'teacher',dialog:null,cloudLoadError:null};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function today(){return new Date().toLocaleDateString('de-DE');}
function recKey(c,p){return c+'|'+p;} function visibleYears(){const y=Auth.allowedGrades();return y.length?y:[State.year];} function canEdit(){return Auth.canLead(State.year);} function canManageRoster(){return Auth.isAdmin()||Auth.canLead(State.year);}
function scoreToStatus(p,r=24,y=74){return p<=r?'red':p<=y?'yellow':'green';}
function statusPlain(s){return s==='green'?'erreicht':s==='yellow'?'teilweise erreicht':s==='red'?'noch nicht erreicht':'ohne Eintrag';}
function statusLabel(s){return `<span class="statusPill status-${s||'empty'}">${statusPlain(s)}</span>`;}
function teamColor(t){const x=String(t||'').toLowerCase();if(x.includes('blau'))return'blue';if(x.includes('rot')||x.includes('pink'))return'rose';if(x.includes('gelb'))return'amber';if(x.includes('lila')||x.includes('violett'))return'violet';return'mint';}
function filteredPupils(){return (Store.pupils||[]).filter(p=>!p.archived&&Number(p.year||String(p.className).charAt(0))===State.year).filter(p=>State.team==='alle'||p.team===State.team).filter(p=>!State.search||`${p.first} ${p.last} ${p.short}`.toLowerCase().includes(State.search.toLowerCase())).sort((a,b)=>a.last.localeCompare(b.last,'de')||a.first.localeCompare(b.first,'de'));}
function sprintObj(){return Store.sprints.find(s=>s.year===State.year&&s.number===State.sprint)} function sprintName(n){return Store.sprints.find(s=>s.year===State.year&&s.number===n)?.name||`Sprint ${n}`;}
function toast(msg=(typeof Sync!=='undefined'&&Sync.enabled&&Sync.enabled()?'Wird in der Cloud gespeichert …':'Lokal gespeichert'),duration=1800){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toast._timer);toast._timer=setTimeout(()=>t.classList.remove('show'),duration)}
function header(title,hint=''){return `<div class="pageHead"><div><h1>${esc(title)}</h1>${hint?`<div class="hint">${esc(hint)}</div>`:''}</div><span class="badge">KOMPASS 8.5.21</span></div>`;}
const NAV=[['dashboard','⌂','Übersicht'],['calendar','◫','Kalender'],['students','👥','Schüler*innen'],['teams','◉','Teams & Coaching'],['planner','⇄','Einteilungsassistent'],['timetable','📅','Stundenplanung'],['workshop','🧭','Werkstatt'],['core','📘','Kernfächer'],['activities','🎨','Angebote'],['behaviour','⭐','Sozialverhalten'],['leb','📝','LEB'],['admin','⚙️','Verwaltung'],['logs','≡','Protokoll'],['backup','⬇️','Datensicherung']];
function shell(content){const u=Auth.currentUser();State.teacher=u?.name||'';State.role=u?.role||'teacher';const nav=NAV.filter(([v])=>{if(['timetable','logs','backup','admin'].includes(v))return Auth.isAdmin();if(['teams','planner'].includes(v))return Auth.isAdmin()||Auth.canLead(State.year);return true;});document.getElementById('app').innerHTML=`<div class="app"><aside><div class="brand">KOMPASS</div><div class="sub">Version 8.5.21</div><div class="userbox"><b>${esc(u?.name||'')}</b><div class="mini">${esc(u?.username||'')}<br>${u?.role==='admin'?'Admin':u?.role==='leitung'?'Stufenleitung':'Lehrkraft'} · ${Auth.session?.mode==='cloud'?'Cloud':'lokal'}</div><button class="chip" onclick="openPasswordDialog()">Passwort ändern</button><button class="chip" onclick="Auth.logout()">Konto wechseln</button></div><div class="nav">${nav.map(([v,i,l])=>`<button class="${State.view===v?'active':''}" onclick="State.view='${v}';State.pupil=null;if('${v}'==='students')State.team='alle';render()"><span>${i}</span>${l}</button>`).join('')}</div></aside><main>${content}</main></div>`;renderDialog();}
function loginScreen(){
  const localUsers=Auth.localUsers();const needsAdmin=!Auth.cloudConfigured()&&localUsers.length===0;document.getElementById('app').innerHTML=`<div class="loginPage"><div class="loginCard"><div class="brand">KOMPASS</div><div class="sub">Version 8.5.21 · ${Auth.cloudConfigured()?'gemeinsame Cloud-Speicherung':'lokale Einrichtung'}</div>${needsAdmin?`<h1>Ersten Admin anlegen</h1><p>Dieser Schritt richtet den ersten Zugang auf diesem Gerät ein.</p><label>Name</label><input id="login_name" placeholder="z. B. J. Schöne"><label>Benutzername</label><input id="login_user" autocomplete="username"><label>Passwort</label><input id="login_pass" type="password" autocomplete="new-password"><button class="chip dark wide" onclick="firstAdminLogin()">Admin anlegen</button>`:`<h1>Mit dem eigenen Konto anmelden</h1><label>${Auth.cloudConfigured()?'Schul-E-Mail':'Benutzername'}</label><input id="login_user" type="email" inputmode="email" autocapitalize="none" autocomplete="username"><label>Passwort</label><input id="login_pass" type="password" autocomplete="current-password"><label class="check"><input type="checkbox" onchange="togglePasswordVisibility(['login_pass'],this.checked)"> Passwort anzeigen</label><button class="chip dark wide" onclick="doLogin()">Anmelden</button>${Auth.cloudConfigured()?`<p class="mini">Auf gemeinsam genutzten Geräten anschließend immer „Konto wechseln“ wählen.</p>`:''}`}<div id="login_error" class="loginError"></div>${!Auth.cloudConfigured()?`<details class="setupDetails"><summary>Gemeinsame Speicherung einrichten</summary><p class="mini">Für mehrere Geräte wird Supabase benötigt. URL und öffentlicher Anon-Key werden nur auf diesem Gerät gespeichert.</p><label>Supabase URL</label><input id="cloud_url"><label>Anon Key</label><textarea id="cloud_key"></textarea><button class="chip" onclick="saveCloudSetup()">Cloud verbinden</button></details>`:''}</div></div>`;
}
function togglePasswordVisibility(ids,visible){for(const id of ids){const field=document.getElementById(id);if(field)field.type=visible?'text':'password'}}
function openPasswordDialog(){State.dialog={mode:'password'};renderDialog()}
function renderPasswordDialog(target){target.innerHTML=`<div class="dialogBackdrop"><div class="dialog"><div class="dialogHead"><h2>Passwort sicher ändern</h2><button class="iconBtn" onclick="State.dialog=null;renderDialog()">×</button></div><p>Das bisherige Passwort wird zuerst geprüft. Das neue Passwort wird erst als erfolgreich gemeldet, wenn auch eine neue Anmeldung damit bestätigt wurde.</p><label>Bisheriges Passwort</label><input id="own_password_current" type="password" autocomplete="current-password"><label>Neues Passwort</label><input id="own_password_1" type="password" autocomplete="new-password" minlength="10"><label>Neues Passwort wiederholen</label><input id="own_password_2" type="password" autocomplete="new-password" minlength="10"><label class="check"><input type="checkbox" onchange="togglePasswordVisibility(['own_password_current','own_password_1','own_password_2'],this.checked)"> Passwörter anzeigen</label><p class="mini">Mindestens 10 Zeichen. Verwende kein Passwort, das du bereits für ein anderes Konto nutzt.</p><button class="chip dark" onclick="saveOwnPassword()">Ändern und Anmeldung prüfen</button><button class="chip" onclick="State.dialog=null;renderDialog()">Abbrechen</button><div id="own_password_error" class="loginError"></div></div></div>`}
async function saveOwnPassword(){const err=document.getElementById('own_password_error'),current=document.getElementById('own_password_current').value,a=document.getElementById('own_password_1').value,b=document.getElementById('own_password_2').value;try{if(a!==b)throw new Error('Die beiden neuen Eingaben stimmen nicht überein.');if(err)err.textContent='Bisheriges Passwort und neue Anmeldung werden geprüft …';await Auth.changeOwnPassword(current,a);State.dialog=null;toast('Passwort geändert und neue Anmeldung geprüft',5000);render()}catch(e){if(err)err.textContent=e?.message||String(e)}}
function cloudLoadErrorScreen(){const localCount=(Store.data?.pupils||[]).length;document.getElementById('app').innerHTML=`<div class="loginPage"><div class="loginCard"><div class="brand">KOMPASS</div><div class="sub">Version 8.5.13 · Cloud-Verbindung</div><h1>Daten konnten nicht sicher geladen werden</h1><p>KOMPASS zeigt zum Schutz keinen leeren Ersatzbestand an und überschreibt keine möglicherweise vorhandenen lokalen Daten.</p><div class="loginError">${esc(State.cloudLoadError||'Unbekannter Cloud-Fehler')}</div>${localCount?`<p><b>${localCount} lokale Schülerdatensätze gefunden.</b></p><button class="chip dark wide" onclick="downloadEmergencyBackup()">Lokalen Notfall-Backup herunterladen</button>`:''}${Auth.isAdmin()?`<div class="section">Geprüften Bestand wiederherstellen</div><p class="mini">Wiederherstellungsdatei auswählen. Die drei Jahrgänge werden gemeinsam gespeichert und anschließend kontrolliert.</p><input id="recovery_file" type="file" accept="application/json,.json" onchange="restoreEmergencyFile(this.files[0])"><div id="recovery_status" class="mini"></div>`:''}<button class="chip wide" onclick="retryCloudLoad()">Erneut laden</button><button class="chip wide" onclick="Auth.logout()">Abmelden</button></div></div>`;}
function downloadEmergencyBackup(){const b=new Blob([JSON.stringify(Store.exportData(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`KOMPASS_NOTFALL_BACKUP_${new Date().toISOString().slice(0,10)}.json`;a.click();}
async function retryCloudLoad(){State.cloudLoadError=null;try{await Sync.pull();render()}catch(e){State.cloudLoadError=e?.message||String(e);render()}}
async function restoreEmergencyFile(file){if(!file)return;const status=document.getElementById('recovery_status');if(status)status.textContent='Wiederherstellung und Kontrollprüfung laufen …';try{const data=JSON.parse(await file.text()),counts=await Sync.restoreBackupData(data);State.cloudLoadError=null;toast('Cloudbestand vollständig wiederhergestellt',4000);render();alert(`Wiederherstellung erfolgreich: Jahrgang 5: ${counts[5]}, Jahrgang 6: ${counts[6]}, Jahrgang 7: ${counts[7]}.`)}catch(e){State.cloudLoadError='Wiederherstellung fehlgeschlagen: '+(e?.message||String(e));render()}}
function loginErr(e){const x=document.getElementById('login_error');if(x)x.textContent=e?.message||String(e)}
async function firstAdminLogin(){try{await Auth.createFirstAdmin(document.getElementById('login_name').value,document.getElementById('login_user').value,document.getElementById('login_pass').value);render()}catch(e){loginErr(e)}}
async function doLogin(){try{if(Auth.cloudConfigured()){if(!Auth.cloudClient)await Auth.initCloud();await Auth.cloudLogin(document.getElementById('login_user').value,document.getElementById('login_pass').value)}else await Auth.localLogin(document.getElementById('login_user').value,document.getElementById('login_pass').value);render()}catch(e){loginErr(e)}}
function showSignup(){loginErr(new Error('Neue Kollegiumskonten werden durch einen Admin in Verwaltung → Benutzer angelegt.'));}
async function doSignup(){loginErr(new Error('Neue Kollegiumskonten werden durch einen Admin angelegt.'));}
async function saveCloudSetup(){try{await Auth.saveCloudConfig(document.getElementById('cloud_url').value,document.getElementById('cloud_key').value)}catch(e){loginErr(e)}}
function dashboard(){const ps=filteredPupils(),assignments=(Store.assignments||[]).filter(a=>a.year===State.year),own=Auth.currentUser()?.coachTeams?.[State.year]||Auth.currentUser()?.coachTeams?.[String(State.year)]||'';shell(header('Übersicht','Schülerdaten, Einteilungen und Lernentwicklung an einem Ort.')+coachReminderHtml(State.year)+`<div class="grid"><div class="tile blueTile" onclick="State.view='students';render()"><b>${ps.length} Schüler*innen</b><span>${own?'Meine Lerngruppe · '+esc(own):'Jahrgang '+State.year}</span><i>👥</i></div><div class="tile violetTile" onclick="State.view='planner';render()"><b>${assignments.length} Einteilungsrunden</b><span>Sprints und Clubs</span><i>⇄</i></div><div class="tile mintTile" onclick="State.view='activities';render()"><b>${Store.activities.length} Angebote</b><span>Kreativband & besondere Angebote</span><i>🎨</i></div></div><div class="section">Jahrgang auswählen</div><div class="toolbar"><select onchange="State.year=Number(this.value);State.team='alle';render()">${visibleYears().map(y=>`<option value="${y}" ${State.year===y?'selected':''}>Jahrgang ${y}</option>`).join('')}</select></div>`) }
function backup(){shell(header('Datensicherung','Daten sichern oder eine bestehende Sicherung einspielen.')+`<div class="grid2"><div class="card"><h2>Sicherung herunterladen</h2><p>Enthält alle Schülerdaten, Bewertungen, Historien und Einteilungen.</p><button class="chip dark" onclick="downloadBackup()">Datensicherung herunterladen</button></div><div class="card"><h2>Sicherung einspielen</h2><input type="file" accept="application/json" onchange="restoreBackup(this.files[0])"></div></div>${Auth.isAdmin()?`<div class="card" style="margin-top:18px"><h2>Notfall-Wiederherstellung</h2><p>Geprüften Schülerbestand direkt und kontrolliert in der Cloud wiederherstellen.</p><input id="recovery_file" type="file" accept="application/json,.json" onchange="restoreEmergencyFile(this.files[0])"><div id="recovery_status" class="mini"></div></div>`:''}`)}
function downloadBackup(){const b=new Blob([JSON.stringify(Store.exportData(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`KOMPASS_8_3_5_${new Date().toISOString().slice(0,10)}.json`;a.click();}
function restoreBackup(f){if(!f)return;const r=new FileReader();r.onload=()=>{try{if(Store.importData(JSON.parse(r.result))){toast('Sicherung eingespielt');render()}}catch(e){alert('Datei konnte nicht gelesen werden.')}};r.readAsText(f);}

function renderKeepingFocus(id){
  const old=document.getElementById(id),start=old?.selectionStart,end=old?.selectionEnd;
  render();
  const next=document.getElementById(id);
  if(next){next.focus({preventScroll:true});try{next.setSelectionRange(start??next.value.length,end??next.value.length)}catch(_e){}}
}
function render(){if(!Auth.isLoggedIn())return loginScreen();if(State.cloudLoadError)return cloudLoadErrorScreen();if(State.view==='dashboard')return dashboard();if(State.view==='calendar')return calendar();if(State.view==='students')return students();if(State.view==='teams')return teamManagement();if(State.view==='planner')return planner();if(State.view==='timetable')return timetable();if(State.view==='workshop')return workshop();if(State.view==='core')return coreSubjects();if(State.view==='activities')return activities();if(State.view==='behaviour')return behaviour();if(State.view==='leb')return leb();if(State.view==='admin')return admin();if(State.view==='logs')return logs();if(State.view==='backup')return backup();dashboard();}
