const BEHAVIOUR_FIELDS=[['selfDirected','Selbstständigkeit'],['concentration','Konzentration'],['organization','Organisation'],['timeManagement','Zeitmanagement'],['selfCheck','Selbstkontrolle'],['asksHelp','Hilfe einholen'],['helpsOthers','Anderen helfen'],['settings','Umgang mit Lernsettings']];
let behaviourPupil=null;
function behaviour(){
  const pupils=filteredPupils(); if(!behaviourPupil&&pupils[0])behaviourPupil=pupils[0].id; const p=Store.pupils.find(x=>x.id===behaviourPupil)||pupils[0];
  let content=header('Arbeits- & Sozialverhalten','Wenige klare Einschätzungen und TeamStar-Karten als Grundlage für den LEB.');
  content+=`<div class="toolbar formgrid"><div><label>Jahrgang</label><select onchange="State.year=Number(this.value);behaviourPupil=null;render()">${[5,6,7].map(y=>`<option value="${y}" ${State.year===y?'selected':''}>Jahrgang ${y}</option>`).join('')}</select></div><div><label>Team</label><select onchange="State.team=this.value;behaviourPupil=null;render()"><option value="alle">alle Teams</option>${TEAMS.map(t=>`<option ${State.team===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Schüler*in</label><select onchange="behaviourPupil=this.value;render()">${pupils.map(x=>`<option value="${x.id}" ${p&&p.id===x.id?'selected':''}>${esc(x.short)}</option>`).join('')}</select></div></div>`;
  if(!p){content+='<div class="card empty">Keine Schüler*innen vorhanden.</div>';shell(content);return;}
  const b=Store.behaviour[p.id]||{ratings:{},teamStars:0,note:''};
  content+=`<div class="card"><h2>${esc(p.short)}</h2><table class="studentTable"><thead><tr><th>Bereich</th><th>Einschätzung</th></tr></thead><tbody>${BEHAVIOUR_FIELDS.map(([key,label])=>`<tr><td><b>${label}</b></td><td><select onchange="saveBehaviour('${p.id}','${key}',this.value)"><option value="">—</option>${['braucht Begleitung','teilweise selbstständig','meist sicher','besonders ausgeprägt'].map(v=>`<option ${b.ratings?.[key]===v?'selected':''}>${v}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table><div class="formgrid"><div><label>Volle TeamStar-Karten (0–3)</label><input type="number" min="0" max="3" value="${b.teamStars||0}" onchange="saveBehaviourMeta('${p.id}','teamStars',Math.max(0,Math.min(3,Number(this.value))))"></div><div><label>Ergänzende Beobachtung</label><textarea onchange="saveBehaviourMeta('${p.id}','note',this.value)">${esc(b.note||'')}</textarea></div></div></div>`;
  shell(content);
}
function saveBehaviour(pupilId,key,value){const b=Store.behaviour[pupilId]||{ratings:{},teamStars:0,note:''}; b.ratings=b.ratings||{}; b.ratings[key]=value; Store.behaviour[pupilId]=b; Store.save(); toast();}
function saveBehaviourMeta(pupilId,key,value){const b=Store.behaviour[pupilId]||{ratings:{},teamStars:0,note:''}; b[key]=value; Store.behaviour[pupilId]=b; Store.save(); toast();}
