const BEHAVIOUR_GROUPS=[
 ['Lernatelier',['arbeitet selbstständig und motiviert','arbeitet überwiegend selbstständig','benötigt gelegentlich Unterstützung','muss häufig motiviert werden']],
 ['Konzentration',['nutzt die Arbeitszeit sinnvoll','arbeitet meist konzentriert','lässt sich leicht ablenken','beendet Aufgaben selten']],
 ['Organisation',['arbeitet strukturiert und organisiert','hält Materialien und Arbeitsplatz in Ordnung','verliert gelegentlich den Überblick','benötigt häufig Hilfe bei der Planung']],
 ['Zusammenarbeit',['arbeitet konstruktiv mit anderen zusammen','hilft anderen zuverlässig','nimmt Hilfe gut an','beteiligt sich wenig an der Zusammenarbeit']],
 ['Selbstkontrolle',['kontrolliert Ergebnisse sorgfältig','verbessert Fehler selbstständig','benötigt Erinnerungen zur Kontrolle']]
];let behaviourPupil=null;
function behaviour(){const pupils=filteredPupils();if(!behaviourPupil&&pupils[0])behaviourPupil=pupils[0].id;const p=Store.pupils.find(x=>x.id===behaviourPupil)||pupils[0];let content=header('Arbeits- & Sozialverhalten');content+=`<div class="toolbar formgrid"><div><label>Jahrgang</label><select onchange="State.year=Number(this.value);behaviourPupil=null;render()">${[5,6,7].map(y=>`<option value="${y}" ${State.year===y?'selected':''}>Jahrgang ${y}</option>`).join('')}</select></div><div><label>Team</label><select onchange="State.team=this.value;behaviourPupil=null;render()"><option value="alle">alle Teams</option>${TEAMS.map(t=>`<option ${State.team===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Schüler*in</label><select onchange="behaviourPupil=this.value;render()">${pupils.map(x=>`<option value="${x.id}" ${p&&p.id===x.id?'selected':''}>${esc(x.short)}</option>`).join('')}</select></div></div>`;if(!p){shell(content+'<div class="card empty">Keine Schüler*innen vorhanden.</div>');return;}const b=Store.behaviour[p.id]||{observations:[],teamStars:0,note:''};content+=`<div class="card"><h2>${esc(p.short)}</h2>${BEHAVIOUR_GROUPS.map(([title,items])=>`<div class="observationGroup"><b>${title}</b><div class="observationChoices">${items.map(x=>`<button class="observationBtn ${(b.observations||[]).includes(x)?'selected':''}" onclick="toggleObservation('${p.id}','${esc(x)}')">${(b.observations||[]).includes(x)?'✓ ':''}${x}</button>`).join('')}</div></div>`).join('')}<div class="formgrid"><div><label>Volle TeamStar-Karten (0–3)</label><input type="number" min="0" max="3" value="${b.teamStars||0}" onchange="saveBehaviourMeta('${p.id}','teamStars',Math.max(0,Math.min(3,Number(this.value))))"></div><div><label>Notiz (optional)</label><textarea onchange="saveBehaviourMeta('${p.id}','note',this.value)">${esc(b.note||'')}</textarea></div></div></div>`;shell(content);}
function toggleObservation(id,text){const b=Store.behaviour[id]||{observations:[],teamStars:0,note:''};b.observations=b.observations||[];b.observations.includes(text)?b.observations=b.observations.filter(x=>x!==text):b.observations.push(text);Store.behaviour[id]=b;Store.save();render();}
function saveBehaviourMeta(id,key,value){const b=Store.behaviour[id]||{observations:[],teamStars:0,note:''};b[key]=value;Store.behaviour[id]=b;Store.save();toast();}
