let CalendarState={date:new Date(),filter:'alle'};
function calPad(n){return String(n).padStart(2,'0')}
function calISO(d){return `${d.getFullYear()}-${calPad(d.getMonth()+1)}-${calPad(d.getDate())}`}
function calendar(){
  const base=new Date(CalendarState.date.getFullYear(),CalendarState.date.getMonth(),1),year=base.getFullYear(),month=base.getMonth(),first=(base.getDay()+6)%7,days=new Date(year,month+1,0).getDate();
  const events=Store.calendarEvents.filter(e=>CalendarState.filter==='alle'||e.category===CalendarState.filter),cats=['Schule','Team','Konferenz','Termin','Deadline','Sonstiges'];
  const cells=[];for(let i=0;i<first;i++)cells.push('<div class="calDay mutedDay"></div>');for(let day=1;day<=days;day++){const d=`${year}-${calPad(month+1)}-${calPad(day)}`,es=events.filter(e=>e.date===d).sort((a,b)=>(a.time||'').localeCompare(b.time||''));cells.push(`<div class="calDay ${d===calISO(new Date())?'todayCell':''}" onclick="openCalendarEvent(null,'${d}')"><div class="calNum">${day}</div>${es.slice(0,4).map(e=>`<button class="calEvent" onclick="event.stopPropagation();openCalendarEvent('${e.id}','${d}')"><b>${esc(e.time||'')}</b> ${esc(e.title)}</button>`).join('')}${es.length>4?`<div class="mini">+${es.length-4} weitere</div>`:''}</div>`)}
  shell(header('Kalender','Gemeinsame Termine, Konferenzen, Deadlines und schulische Ereignisse.')+`<div class="calToolbar"><button class="chip" onclick="calMove(-1)">‹</button><h2>${base.toLocaleDateString('de-DE',{month:'long',year:'numeric'})}</h2><button class="chip" onclick="calMove(1)">›</button><button class="chip dark" onclick="CalendarState.date=new Date();render()">Heute</button><select onchange="CalendarState.filter=this.value;render()"><option value="alle">alle Kategorien</option>${cats.map(c=>`<option ${CalendarState.filter===c?'selected':''}>${c}</option>`).join('')}</select><button class="chip dark" onclick="openCalendarEvent(null,'${calISO(new Date())}')">+ Termin</button></div><div class="calWeekHead">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calGrid">${cells.join('')}</div>`);
}
function calMove(n){CalendarState.date=new Date(CalendarState.date.getFullYear(),CalendarState.date.getMonth()+n,1);render()}
function openCalendarEvent(id,date){State.dialog={mode:'calendar',id,date};renderDialog()}
function renderCalendarDialog(target){const old=State.dialog.id?Store.calendarEvents.find(x=>x.id===State.dialog.id):null,e=old||{title:'',date:State.dialog.date||calISO(new Date()),time:'',endTime:'',category:'Schule',location:'',notes:'',visibility:'all'};target.innerHTML=`<div class="dialogBackdrop"><div class="dialog"><div class="dialogHead"><h2>${old?'Termin bearbeiten':'Termin anlegen'}</h2><button class="iconBtn" onclick="State.dialog=null;renderDialog()">×</button></div><label>Titel</label><input id="cal_title" value="${esc(e.title)}"><div class="formgrid"><div><label>Datum</label><input id="cal_date" type="date" value="${esc(e.date)}"></div><div><label>Beginn</label><input id="cal_time" type="time" value="${esc(e.time)}"></div><div><label>Ende</label><input id="cal_end" type="time" value="${esc(e.endTime)}"></div><div><label>Kategorie</label><select id="cal_cat">${['Schule','Team','Konferenz','Termin','Deadline','Sonstiges'].map(c=>`<option ${e.category===c?'selected':''}>${c}</option>`).join('')}</select></div></div><label>Ort</label><input id="cal_loc" value="${esc(e.location)}"><label>Notizen</label><textarea id="cal_notes">${esc(e.notes)}</textarea><button class="chip dark" onclick="saveCalendarEvent()">Speichern</button>${old?`<button class="chip" onclick="deleteCalendarEvent()">Löschen</button>`:''}</div></div>`}
function saveCalendarEvent(){const old=State.dialog.id?Store.calendarEvents.find(x=>x.id===State.dialog.id):null,e=old||{id:uid('event'),createdAt:new Date().toISOString(),createdBy:Auth.currentUser()?.name||State.teacher};e.title=document.getElementById('cal_title').value.trim();e.date=document.getElementById('cal_date').value;e.time=document.getElementById('cal_time').value;e.endTime=document.getElementById('cal_end').value;e.category=document.getElementById('cal_cat').value;e.location=document.getElementById('cal_loc').value.trim();e.notes=document.getElementById('cal_notes').value.trim();e.updatedAt=new Date().toISOString();e.updatedBy=Auth.currentUser()?.name||State.teacher;if(!e.title||!e.date){alert('Bitte Titel und Datum eintragen.');return}if(!old)Store.calendarEvents.push(e);Store.save('Kalendertermin gespeichert',{target:e.title,date:e.date});State.dialog=null;toast();render()}
function deleteCalendarEvent(){const e=Store.calendarEvents.find(x=>x.id===State.dialog.id);if(!e||!confirm('Termin wirklich löschen?'))return;Store.calendarEvents=Store.calendarEvents.filter(x=>x.id!==e.id);Store.save('Kalendertermin gelöscht',{target:e.title,date:e.date});State.dialog=null;toast('Gelöscht');render()}
function logs(){if(!Auth.isAdmin()){shell(header('Kein Zugriff','Änderungsprotokolle sind nur für Admins sichtbar.'));return}const rows=Store.auditLog.slice().reverse().slice(0,500);shell(header('Änderungsprotokoll','Die letzten 500 protokollierten Änderungen in KOMPASS.')+`<div class="card"><div class="logList">${rows.map(l=>`<div class="logRow"><div><b>${esc(l.action)}</b><div class="mini">${esc(l.user||'System')} · ${new Date(l.at).toLocaleString('de-DE')}</div></div><div class="mini">${esc((l.sections||[]).join(', '))}${l.details?.target?' · '+esc(l.details.target):''}</div></div>`).join('')||'<div class="empty">Noch keine Änderungen protokolliert.</div>'}</div></div>`)}
