const CORE_SUBJECTS = ['Deutsch','Mathematik','Englisch'];
const WORKSHOP_SUBJECTS = ['Geographie','Geschichte','Informatik & Medienbildung','Bildende Kunst','Musik','Biologie','Physik','Technik','AES','WBS','Gemeinschaftskunde'];
const TEAMS = ['Blau','Rot','Gelb','Violett','Grün','Lila','Pink'];
const LEVELS = ['G','M','E'];
const DEFAULT_SCORE_CONFIG = { redMax:24, yellowMax:74 };
const CREATIVE_ROOMS = [
 {id:'room_garden',name:'Schulgarten',icon:'🌱',licenses:['Hochbeet-Führerschein','Aussaat-Führerschein','Kompost-Führerschein']},
 {id:'room_science',name:'NW-Labor',icon:'🧪',licenses:['Mikroskopführerschein','Laborführerschein','Experimentierführerschein']},
 {id:'room_creative',name:'Kreativwerkstatt',icon:'🎨',licenses:['Nähmaschinenführerschein','Plotterführerschein','Textildruck-Führerschein']},
 {id:'room_tech',name:'Technikwerkstatt',icon:'🛠️',licenses:['Werkzeugführerschein','Bohrmaschinenführerschein','Lötführerschein']},
 {id:'room_music',name:'Musicroom',icon:'🎵',licenses:['Keyboard-Basis','Cajón-Basis','Ukulele-Basis']},
 {id:'room_it',name:'IT-Room',icon:'💻',licenses:['Scratch-Programmierschein','Micro:bit-Programmierschein','iPad-Basis']}
];
const PROJECT_TEMPLATES = [
 {id:'project_school',name:'Gemeinsam starten – Wir entdecken unsere Schule',labs:['GeoLab','MediaLab','TechLab','FutureFoodLab','HistoryLab','Bildende Kunst','Musik']},
 {id:'project_romans',name:'Die Römer vor unserer Haustür',labs:['HistoryLab','GeoLab','MediaLab','TechLab','FutureFoodLab','Bildende Kunst','Musik']},
 {id:'project_bread',name:'Vom Korn zum Brot',labs:['FutureFoodLab','GeoLab','MediaLab','TechLab','HistoryLab','Bildende Kunst','Musik']},
 {id:'project_hall',name:'Unsere Stadt Schwäbisch Hall – gestern, heute und morgen',labs:['HistoryLab','GeoLab','MediaLab','TechLab','FutureFoodLab','Bildende Kunst','Musik']}
];
const ENGLISH_5 = [
 ['Sprachliche Mittel – Wortschatz','U1','Ich kann Wörter über mich verstehen und benutzen.'],['Sprachliche Mittel – Wortschatz','U1','Ich kann Wörter aus dem Unterricht und zur Schule verstehen und anwenden.'],['Sprachliche Mittel – Wortschatz','U2','Ich kann Wörter zu Familie und Zuhause verstehen und benutzen.'],['Sprachliche Mittel – Wortschatz','U3','Ich kann Zahlen, Datum und Uhrzeit verstehen und sagen.'],['Sprachliche Mittel – Wortschatz','U3','Ich kann Wörter zu Freizeit und Alltag verstehen und benutzen.'],['Sprachliche Mittel – Wortschatz','U4','Ich kann Orts- und Zeitangaben verstehen und richtig benutzen.'],['Sprachliche Mittel – Wortschatz','U5','Ich kann Wörter zum Wetter und den Jahreszeiten benutzen.'],
 ['Sprachliche Mittel – Grammatik','U1','Ich kann Aufforderungen und Bitten höflich ausdrücken.'],['Sprachliche Mittel – Grammatik','U1','Ich kann Nomen im Singular und Plural anwenden.'],['Sprachliche Mittel – Grammatik','U1','Ich kann das Verb „to be“ und die Kurzformen richtig anwenden.'],['Sprachliche Mittel – Grammatik','U2','Ich kann den s-Genitiv sicher anwenden.'],['Sprachliche Mittel – Grammatik','U2','Ich kann einfache Sätze, Fragen und Verneinungen im Simple Present bilden.'],['Sprachliche Mittel – Grammatik','U5','Ich kann einfache Sätze im Simple Past bilden.'],
 ['Verstehen – Hörverstehen','U1','Ich kann kurze Anweisungen im Unterricht verstehen.'],['Verstehen – Hörverstehen','U1','Ich kann bekannte Wörter und Wendungen verstehen.'],['Verstehen – Hörverstehen','U3','Ich kann wichtige Informationen aus kurzen Hörtexten heraushören.'],['Verstehen – Hörverstehen','U4','Ich kann kurze Gespräche verstehen.'],['Verstehen – Hörverstehen','U5','Ich kann eine Reportage und Interviews verstehen.'],
 ['Verstehen – Leseverstehen','U1','Ich kann kurze Anleitungen und Erklärungen verstehen.'],['Verstehen – Leseverstehen','U1','Ich kann einfachen Texten Informationen entnehmen.'],['Verstehen – Leseverstehen','U2','Ich kann kurze Mitteilungen und Alltagstexte verstehen.'],['Verstehen – Leseverstehen','U2','Ich kann einen Lesetext verstehen.'],['Verstehen – Leseverstehen','U3','Ich kann kurze Szenen verstehen.'],['Verstehen – Leseverstehen','U4','Ich kann sagen, worum es in einem kurzen Text geht.'],['Verstehen – Leseverstehen','U5','Ich kann eine kurze Geschichte verstehen.'],
 ['Sprechen','U1','Ich kann begrüßen, mich verabschieden und vorstellen.'],['Sprechen','U1','Ich kann über meine Schule und meinen Unterricht sprechen.'],['Sprechen','U2','Ich kann über meine Familie sprechen und Fragen beantworten.'],['Sprechen','U2','Ich kann in Sätzen über mich und mein Zuhause sprechen.'],['Sprechen','U3','Ich kann über meinen Tagesablauf und meine Freizeit sprechen.'],['Sprechen','U4','Ich kann einen Weg beschreiben.'],['Sprechen','U5','Ich kann längere Gespräche über mein Umfeld führen.'],
 ['Schreiben','U1','Ich kann Wörter und kurze Sätze richtig schreiben.'],['Schreiben','U1','Ich kann über mich schreiben.'],['Schreiben','U2','Ich kann über meine Familie und mein Zuhause schreiben.'],['Schreiben','U2','Ich kann einfache Fragen schriftlich beantworten.'],['Schreiben','U3','Ich kann über meinen Alltag und meine Freizeit schreiben.'],
 ['Sprachmittlung','U1','Ich kann bekannte englische Wörter auf Deutsch beschreiben.'],['Sprachmittlung','U2','Ich kann kurze englische Aussagen auf Deutsch wiedergeben.'],['Sprachmittlung','U2','Ich kann einzelne bekannte deutsche Wörter auf Englisch sagen.'],['Sprachmittlung','U3','Ich kann einfache deutsche Aussagen auf Englisch wiedergeben.'],['Sprachmittlung','U4','Ich kann einfache Informationen für andere verständlich machen.']
];
function english5Competencies(){return ENGLISH_5.map((x,i)=>({id:'eng5_'+i,type:'core',year:5,sprint:null,subject:'Englisch',category:x[0],area:x[0],unit:x[1],level:'G/M/E',text:x[2],includeInLeb:true,order:(i+1)*10,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''}));}
const SEED = {
 version:'5.0', subjects:[...WORKSHOP_SUBJECTS], coreSubjects:[...CORE_SUBJECTS], projectTemplates:PROJECT_TEMPLATES, creativeRooms:CREATIVE_ROOMS,
 sprints:[1,2,3,4,5].flatMap(n=>[5,6,7].map(y=>({id:`s${y}_${n}`,year:y,number:n,name:n===1?'Gemeinsam starten':`Sprint ${n}`,projectId:n===1?'project_school':'',startDate:'',endDate:''}))),
 pupils:[{id:'p_frank',first:'Frank',last:'Schneider',short:'Frank S.',className:'5a',team:'Blau',color:'blue',coach:'N.O.'}],
 competencies:[...english5Competencies(),
 {id:'w_school_geo',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'GeoLab',subject:'Geographie',category:'Orientierung',area:'Orientierung',level:'G/M/E',text:'Ich kann Lagepläne und Karten nutzen, um mich sicher zu orientieren.',includeInLeb:true,order:10,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_media',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'MediaLab',subject:'Informatik & Medienbildung',category:'Digitale Werkzeuge',area:'Digitale Werkzeuge',level:'G/M/E',text:'Ich kann digitale Werkzeuge zur Recherche, Dokumentation und Präsentation verantwortungsvoll nutzen.',includeInLeb:true,order:20,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_history',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'HistoryLab',subject:'Geschichte',category:'Quellen',area:'Quellen',level:'G/M/E',text:'Ich kann Informationen aus einfachen historischen Quellen gewinnen und dokumentieren.',includeInLeb:true,order:30,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_art',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'Bildende Kunst',subject:'Bildende Kunst',category:'Gestaltung',area:'Gestaltung',level:'G/M/E',text:'Ich kann Informationen übersichtlich visualisieren und Lernprodukte adressatengerecht gestalten.',includeInLeb:true,order:40,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_music',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'Musik',subject:'Musik',category:'Präsentation',area:'Präsentation',level:'G/M/E',text:'Ich kann musikalische oder auditive Elemente für eine gemeinsame Präsentation gestalten.',includeInLeb:true,order:50,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''}
 ]
};