const CORE_SUBJECTS = ['Deutsch','Mathematik','Englisch'];
const WORKSHOP_SUBJECTS = ['Geographie','Geschichte','Informatik & Medienbildung','Bildende Kunst','Musik','Biologie','Physik','Technik','AES','WBS','Gemeinschaftskunde'];
const TEAMS = ['Blau','Rot','Gelb','Violett','Grün','Lila','Pink'];
const LEVELS = ['G','M','E'];
const DEFAULT_SCORE_CONFIG = { redMax:24, yellowMax:74 };
const CREATIVE_ROOMS = [
 {id:'room_garden',name:'Schulgarten',icon:'🌱',licenses:['Hochbeet-Führerschein','Aussaat-Führerschein','Kompost-Führerschein']},
 {id:'room_science',name:'NW-Labor',icon:'🧪',licenses:['Mikroskopführerschein','Laborführerschein','Experimentierführerschein']},
 {id:'room_creative',name:'Kreativwerkstatt',icon:'🎨',licenses:['Nähmaschinenführerschein','Plotterführerschein','Textildruck-Führerschein']},
 {id:'room_tech',name:'Technikwerkstatt',icon:'🛠️',licenses:['Werkzeugführerschein','Bohrmaschinenführerschein','Lötführerschein']},
 {id:'room_music',name:'Musicroom',icon:'🎵',licenses:['Keyboard-Basis','Cajón-Basis','Ukulele-Basis']},
 {id:'room_it',name:'IT-Room',icon:'💻',licenses:['Scratch-Programmierschein','Micro:bit-Programmierschein','iPad-Basis']}
];
const PROJECT_TEMPLATES = [
 {id:'project_school',name:'Gemeinsam starten – Wir entdecken unsere Schule',labs:['GeoLab','MediaLab','TechLab','FutureFoodLab','HistoryLab','Bildende Kunst','Musik']},
 {id:'project_romans',name:'Die Römer vor unserer Haustür',labs:['HistoryLab','GeoLab','MediaLab','TechLab','FutureFoodLab','Bildende Kunst','Musik']},
 {id:'project_bread',name:'Vom Korn zum Brot',labs:['FutureFoodLab','GeoLab','MediaLab','TechLab','HistoryLab','Bildende Kunst','Musik']},
 {id:'project_hall',name:'Unsere Stadt Schwäbisch Hall – gestern, heute und morgen',labs:['HistoryLab','GeoLab','MediaLab','TechLab','FutureFoodLab','Bildende Kunst','Musik']}
];
const ENGLISH_5 = [
 ['Sprachliche Mittel – Wortschatz','U1','Ich kann Wörter über mich verstehen und benutzen.'],['Sprachliche Mittel – Wortschatz','U1','Ich kann Wörter aus dem Unterricht und zur Schule verstehen und anwenden.'],['Sprachliche Mittel – Wortschatz','U2','Ich kann Wörter zu Familie und Zuhause verstehen und benutzen.'],['Sprachliche Mittel – Wortschatz','U3','Ich kann Zahlen, Datum und Uhrzeit verstehen und sagen.'],['Sprachliche Mittel – Wortschatz','U3','Ich kann Wörter zu Freizeit und Alltag verstehen und benutzen.'],['Sprachliche Mittel – Wortschatz','U4','Ich kann Orts- und Zeitangaben verstehen und richtig benutzen.'],['Sprachliche Mittel – Wortschatz','U5','Ich kann Wörter zum Wetter und den Jahreszeiten benutzen.'],
 ['Sprachliche Mittel – Grammatik','U1','Ich kann Aufforderungen und Bitten höflich ausdrücken.'],['Sprachliche Mittel – Grammatik','U1','Ich kann Nomen im Singular und Plural anwenden.'],['Sprachliche Mittel – Grammatik','U1','Ich kann das Verb „to be“ und die Kurzformen richtig anwenden.'],['Sprachliche Mittel – Grammatik','U2','Ich kann den s-Genitiv sicher anwenden.'],['Sprachliche Mittel – Grammatik','U2','Ich kann einfache Sätze, Fragen und Verneinungen im Simple Present bilden.'],['Sprachliche Mittel – Grammatik','U5','Ich kann einfache Sätze im Simple Past bilden.'],
 ['Verstehen – Hörverstehen','U1','Ich kann kurze Anweisungen im Unterricht verstehen.'],['Verstehen – Hörverstehen','U1','Ich kann bekannte Wörter und Wendungen verstehen.'],['Verstehen – Hörverstehen','U3','Ich kann wichtige Informationen aus kurzen Hörtexten heraushören.'],['Verstehen – Hörverstehen','U4','Ich kann kurze Gespräche verstehen.'],['Verstehen – Hörverstehen','U5','Ich kann eine Reportage und Interviews verstehen.'],
 ['Verstehen – Leseverstehen','U1','Ich kann kurze Anleitungen und Erklärungen verstehen.'],['Verstehen – Leseverstehen','U1','Ich kann einfachen Texten Informationen entnehmen.'],['Verstehen – Leseverstehen','U2','Ich kann kurze Mitteilungen und Alltagstexte verstehen.'],['Verstehen – Leseverstehen','U2','Ich kann einen Lesetext verstehen.'],['Verstehen – Leseverstehen','U3','Ich kann kurze Szenen verstehen.'],['Verstehen – Leseverstehen','U4','Ich kann sagen, worum es in einem kurzen Text geht.'],['Verstehen – Leseverstehen','U5','Ich kann eine kurze Geschichte verstehen.'],
 ['Sprechen','U1','Ich kann begrüßen, mich verabschieden und vorstellen.'],['Sprechen','U1','Ich kann über meine Schule und meinen Unterricht sprechen.'],['Sprechen','U2','Ich kann über meine Familie sprechen und Fragen beantworten.'],['Sprechen','U2','Ich kann in Sätzen über mich und mein Zuhause sprechen.'],['Sprechen','U3','Ich kann über meinen Tagesablauf und meine Freizeit sprechen.'],['Sprechen','U4','Ich kann einen Weg beschreiben.'],['Sprechen','U5','Ich kann längere Gespräche über mein Umfeld führen.'],
 ['Schreiben','U1','Ich kann Wörter und kurze Sätze richtig schreiben.'],['Schreiben','U1','Ich kann über mich schreiben.'],['Schreiben','U2','Ich kann über meine Familie und mein Zuhause schreiben.'],['Schreiben','U2','Ich kann einfache Fragen schriftlich beantworten.'],['Schreiben','U3','Ich kann über meinen Alltag und meine Freizeit schreiben.'],
 ['Sprachmittlung','U1','Ich kann bekannte englische Wörter auf Deutsch beschreiben.'],['Sprachmittlung','U2','Ich kann kurze englische Aussagen auf Deutsch wiedergeben.'],['Sprachmittlung','U2','Ich kann einzelne bekannte deutsche Wörter auf Englisch sagen.'],['Sprachmittlung','U3','Ich kann einfache deutsche Aussagen auf Englisch wiedergeben.'],['Sprachmittlung','U4','Ich kann einfache Informationen für andere verständlich machen.']
];
function english5Competencies(){return ENGLISH_5.map((x,i)=>({id:'eng5_'+i,type:'core',year:5,sprint:null,subject:'Englisch',category:x[0],area:x[0],unit:x[1],level:'G/M/E',text:x[2],includeInLeb:true,order:(i+1)*10,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''}));}
const SEED = {
 version:'8.3.2', subjects:[...WORKSHOP_SUBJECTS], coreSubjects:[...CORE_SUBJECTS], projectTemplates:PROJECT_TEMPLATES, creativeRooms:CREATIVE_ROOMS,
 sprints:[1,2,3,4,5].flatMap(n=>[5,6,7].map(y=>({id:`s${y}_${n}`,year:y,number:n,name:n===1?'Gemeinsam starten':`Sprint ${n}`,projectId:n===1?'project_school':'',startDate:'',endDate:''}))),
 pupils:[
  {id:'p5_blau_1',first:'Alexander',last:'Gerich',short:'Alexander G.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_2',first:'Ali',last:'Kamay',short:'Ali K.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_3',first:'Artina',last:'Arifi',short:'Artina A.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_4',first:'Ayat',last:'Murad',short:'Ayat M.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_5',first:'Devran',last:'Selcuk',short:'Devran S.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_6',first:'Elisa',last:'Bohn',short:'Elisa B.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_7',first:'Emma',last:'Helmedach',short:'Emma H.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_8',first:'Jan',last:'Samsel',short:'Jan S.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_9',first:'Kobra',last:'Shayman',short:'Kobra S.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_10',first:'Maria',last:'Murad',short:'Maria M.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_11',first:'Marie',last:'Herterich',short:'Marie H.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_12',first:'Marisa',last:'Befus',short:'Marisa B.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_13',first:'Max',last:'Feldwieser',short:'Max F.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_14',first:'Melita',last:'Puzaniaite',short:'Melita P.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_15',first:'Mick',last:'Dambach',short:'Mick D.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_16',first:'Noah',last:'Lang',short:'Noah L.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_17',first:'Pelle',last:'Weiß',short:'Pelle W.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_18',first:'Sophie',last:'Kromm',short:'Sophie K.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_19',first:'Tom',last:'Feldwieser',short:'Tom F.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_20',first:'Tomas',last:'Simic',short:'Tomas S.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_21',first:'Yefim',last:'Kharin',short:'Yefim K.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_blau_22',first:'Yusuf',last:'Pehlivan',short:'Yusuf P.',className:'5a',year:5,team:'Blau',color:teamColor('Blau'),coach:''},
  {id:'p5_rot_1',first:'Alessio',last:'Scheibner',short:'Alessio S.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_2',first:'Annsophie',last:'Krauter',short:'Annsophie K.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_3',first:'Björn',last:'Hinz',short:'Björn H.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_4',first:'Daniil',last:'Lev',short:'Daniil L.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_5',first:'Darius',last:'Cucu',short:'Darius C.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_6',first:'Elia',last:'Grözinger',short:'Elia G.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_7',first:'Greta',last:'Hulsch',short:'Greta H.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_8',first:'Hannah',last:'Schibalski',short:'Hannah S.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_9',first:'Jakob',last:'Kaiser',short:'Jakob K.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_10',first:'Jana',last:'Feres',short:'Jana F.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_11',first:'Joko',last:'Meissner',short:'Joko M.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_12',first:'Laurin',last:'Skaritzky',short:'Laurin S.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_13',first:'Leonie',last:'Vogt',short:'Leonie V.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_14',first:'Lilly',last:'Nguyen',short:'Lilly N.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_15',first:'Luca',last:'Stimpfig',short:'Luca S.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_16',first:'Ludwig',last:'Lenz',short:'Ludwig L.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_17',first:'Mats',last:'Wolf',short:'Mats W.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_18',first:'Mohamad',last:'Asaad',short:'Mohamad A.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_19',first:'Mohammed',last:'Mussa',short:'Mohammed M.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_20',first:'Oscar',last:'Stecher',short:'Oscar S.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_21',first:'Philipp',last:'Hain',short:'Philipp H.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_22',first:'Robert',last:'Markgraf',short:'Robert M.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_23',first:'Ruslan',last:'Yahodkin',short:'Ruslan Y.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_24',first:'Sophie',last:'Vetter',short:'Sophie V.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_25',first:'Steck',last:'Jamilya',short:'Steck J.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_26',first:'Tim',last:'Burkhart',short:'Tim B.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_rot_27',first:'Yasin',last:'Arslan',short:'Yasin A.',className:'5b',year:5,team:'Rot',color:teamColor('Rot'),coach:''},
  {id:'p5_gelb_1',first:'Adrian',last:'Dohm',short:'Adrian D.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_2',first:'Alejandro',last:'Hennig',short:'Alejandro H.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_3',first:'Ammar',last:'Abdulrahem',short:'Ammar A.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_4',first:'Ania',last:'Hartel',short:'Ania H.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_5',first:'Anton',last:'Zürn',short:'Anton Z.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_6',first:'Elias',last:'Schoch',short:'Elias S.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_7',first:'Emily',last:'Brünnler',short:'Emily B.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_8',first:'Estelle',last:'Zwilling',short:'Estelle Z.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_9',first:'Finnja',last:'Stadelmaier',short:'Finnja S.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_10',first:'Gamal',last:'Zedan',short:'Gamal Z.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_11',first:'Johann',last:'Sommer',short:'Johann S.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_12',first:'Letizia',last:'Ligorio',short:'Letizia L.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_13',first:'Lilli',last:'Wirth',short:'Lilli W.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_14',first:'Lotta',last:'Halfter',short:'Lotta H.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_15',first:'Marius',last:'Strobel',short:'Marius S.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_16',first:'Mateo',last:'Perko',short:'Mateo P.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_17',first:'Merida',last:'Schaupp',short:'Merida S.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_18',first:'Mohammad',last:'Fakkas',short:'Mohammad F.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_19',first:'Noah',last:'Hartel',short:'Noah H.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_20',first:'Ole',last:'Finger',short:'Ole F.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_21',first:'Ole',last:'Gallistl',short:'Ole G.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_22',first:'Philipp',last:'Bohn',short:'Philipp B.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_23',first:'Selim',last:'Brenner',short:'Selim B.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_24',first:'Yahya',last:'Asaad',short:'Yahya A.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_25',first:'Yannik',last:'Tschirner',short:'Yannik T.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_gelb_26',first:'Yona',last:'Wieland',short:'Yona W.',className:'5c',year:5,team:'Gelb',color:teamColor('Gelb'),coach:''},
  {id:'p5_violett_1',first:'Adam',last:'Hasselbach',short:'Adam H.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_2',first:'Amelie',last:'Fischer',short:'Amelie F.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_3',first:'Anja',last:'Grauer',short:'Anja G.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_4',first:'Anni',last:'Rickert',short:'Anni R.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_5',first:'Berivan',last:'Cardakli',short:'Berivan C.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_6',first:'Cosmo',last:'Neitzel',short:'Cosmo N.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_7',first:'David',last:'Ferkovic',short:'David F.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_8',first:'Elena',last:'Grünberg',short:'Elena G.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_9',first:'Emma',last:'Stiner',short:'Emma S.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_10',first:'Faye',last:'Schramm',short:'Faye S.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_11',first:'Godbless',last:'Osasehgie',short:'Godbless O.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_12',first:'Ida',last:'Joos',short:'Ida J.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_13',first:'Lena',last:'Vogel',short:'Lena V.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_14',first:'Leticia',last:'Rimer',short:'Leticia R.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_15',first:'Lija',last:'Hammer',short:'Lija H.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_16',first:'Lilly',last:'Orlamünder',short:'Lilly O.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_17',first:'Mahrima',last:'Jamal',short:'Mahrima J.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_18',first:'Marie',last:'Glaser',short:'Marie G.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_19',first:'Merle',last:'Poser',short:'Merle P.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_20',first:'Muhammad',last:'Asif',short:'Muhammad A.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_21',first:'Naemi',last:'Buchstab',short:'Naemi B.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_22',first:'Niklas',last:'Haas',short:'Niklas H.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_23',first:'Roman',last:'Gorst',short:'Roman G.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_24',first:'Samu',last:'Schmidt',short:'Samu S.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_25',first:'Sarina',last:'Lawendel',short:'Sarina L.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_26',first:'Snejana',last:'Hammer',short:'Snejana H.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_violett_27',first:'Yousseh',last:'Rawy',short:'Yousseh R.',className:'5d',year:5,team:'Violett',color:teamColor('Violett'),coach:''},
  {id:'p5_grun_1',first:'Amely',last:'Erhardt',short:'Amely E.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_2',first:'Arian',last:'Ali',short:'Arian A.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_3',first:'Chayanis',last:'Dähn',short:'Chayanis D.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_4',first:'Denisa',last:'Nechifor',short:'Denisa N.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_5',first:'Emma',last:'Fink',short:'Emma F.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_6',first:'Estelle',last:'Wins',short:'Estelle W.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_7',first:'Finn',last:'Hannemann',short:'Finn H.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_8',first:'Greta',last:'Fritz',short:'Greta F.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_9',first:'Ilin',last:'Alhamad',short:'Ilin A.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_10',first:'Jannis',last:'Popandopoulo',short:'Jannis P.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_11',first:'Janosch',last:'Marko',short:'Janosch M.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_12',first:'Jonas',last:'Köhler',short:'Jonas K.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_13',first:'Kyryl',last:'Kuklenko',short:'Kyryl K.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_14',first:'Lauris',last:'Möger',short:'Lauris M.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_15',first:'Leni',last:'Schuchhardt',short:'Leni S.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_16',first:'Liz',last:'Vollheide',short:'Liz V.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_17',first:'Louis',last:'Schickner',short:'Louis S.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_18',first:'Luis',last:'Weber',short:'Luis W.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_19',first:'Lukas',last:'Leutert',short:'Lukas L.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_20',first:'Maher',last:'Hana',short:'Maher H.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_21',first:'Malea',last:'Braun',short:'Malea B.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_22',first:'Max',last:'Weller',short:'Max W.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_23',first:'Paul',last:'Roth',short:'Paul R.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_24',first:'Roj',last:'Elias',short:'Roj E.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_25',first:'Sabrin',last:'Alkalash',short:'Sabrin A.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_26',first:'Slawa',last:'Novosseltsev',short:'Slawa N.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_27',first:'Sofia',last:'Gierlowski',short:'Sofia G.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p5_grun_28',first:'Theo',last:'Ackermann',short:'Theo A.',className:'5e',year:5,team:'Grün',color:teamColor('Grün'),coach:''},
  {id:'p6_hellblau_1',first:'Antonia-Andrea-Izabela',last:'Urjuma',short:'Antonia-Andrea-Izabela U.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_2',first:'Bennet',last:'Thaqi',short:'Bennet T.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_3',first:'Bunyamin',last:'Touray',short:'Bunyamin T.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_4',first:'Delisha',last:'Merkle',short:'Delisha M.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_5',first:'Elias',last:'Orlamünder',short:'Elias O.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_6',first:'Ella',last:'Schoch',short:'Ella S.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_7',first:'Finn-Luca',last:'Preussler',short:'Finn-Luca P.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_8',first:'Fiona',last:'Fritz',short:'Fiona F.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_9',first:'Juliet',last:'Nwammadu',short:'Juliet N.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_10',first:'Katja',last:'Schreyer',short:'Katja S.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_11',first:'Mia',last:'Weiss',short:'Mia W.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_hellblau_12',first:'Sabirin',last:'Mohamed',short:'Sabirin M.',className:'6a',year:6,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:'Claudia Rock'},
  {id:'p6_dunkelblau_1',first:'Cristina',last:'Haag',short:'Cristina H.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_2',first:'Ela',last:'Gülmez',short:'Ela G.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_3',first:'Elisey',last:'Mamaev',short:'Elisey M.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_4',first:'Emma',last:'Hilkert',short:'Emma H.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_5',first:'Henri',last:'Koppenhöfer',short:'Henri K.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_6',first:'Kudret',last:'Kabar',short:'Kudret K.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_7',first:'Lara',last:'Braun',short:'Lara B.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_8',first:'Leonie',last:'Heiß',short:'Leonie H.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_9',first:'Lisa',last:'Schoch',short:'Lisa S.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_10',first:'Lukas',last:'Harsch',short:'Lukas H.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_11',first:'Mikka',last:'Lenz',short:'Mikka L.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_12',first:'Mohamed',last:'Ali',short:'Mohamed A.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_dunkelblau_13',first:'Rohat',last:'Awso',short:'Rohat A.',className:'6a',year:6,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:'Nicole Oursin'},
  {id:'p6_hellrot_1',first:'Charlene',last:'Scheufele',short:'Charlene S.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_2',first:'Darius',last:'Nechifor',short:'Darius N.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_3',first:'David',last:'Sieger',short:'David S.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_4',first:'Lea',last:'Schimminger',short:'Lea S.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_5',first:'Leon',last:'Wittich',short:'Leon W.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_6',first:'Mika',last:'Walter',short:'Mika W.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_7',first:'Nevia',last:'Yildiz',short:'Nevia Y.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_8',first:'Selenita',last:'Vladimirova',short:'Selenita V.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_9',first:'Shane',last:'Soffner',short:'Shane S.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_hellrot_10',first:'Tanja',last:'Prokisch',short:'Tanja P.',className:'6b',year:6,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:'Marcel Moser'},
  {id:'p6_dunkelrot_1',first:'Asil',last:'Hassan',short:'Asil H.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_2',first:'Eneas',last:'Erlewein',short:'Eneas E.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_3',first:'Enes',last:'Cakir',short:'Enes C.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_4',first:'Giuliana',last:'Buchner',short:'Giuliana B.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_5',first:'Jozsef Remusz',last:'Dima',short:'Jozsef Remusz D.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_6',first:'Julia',last:'Jahr',short:'Julia J.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_7',first:'Kristijan',last:'Ferkovic',short:'Kristijan F.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_8',first:'Leandro',last:'Makrygiannis',short:'Leandro M.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_9',first:'Luke',last:'Hettesheimer',short:'Luke H.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_10',first:'Mayleen',last:'Allweiler',short:'Mayleen A.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_11',first:'Melissa',last:'Krüger',short:'Melissa K.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_12',first:'Mihrimah',last:'Aygün',short:'Mihrimah A.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_13',first:'Osman Enes',last:'Ilhan',short:'Osman Enes I.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_14',first:'Sofia',last:'Vasileiou',short:'Sofia V.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_dunkelrot_15',first:'Sofiia',last:'Gerei',short:'Sofiia G.',className:'6b',year:6,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:'Dagmar Zwilling'},
  {id:'p6_hellgelb_1',first:'Aurel',last:'Strobel',short:'Aurel S.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_2',first:'David',last:'Tiedt',short:'David T.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_3',first:'Davin',last:'Martel',short:'Davin M.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_4',first:'Emma',last:'Zimmermann',short:'Emma Z.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_5',first:'Fiona',last:'Sulejmani',short:'Fiona S.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_6',first:'Hanna',last:'Markova',short:'Hanna M.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_7',first:'Kevin',last:'Vapler',short:'Kevin V.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_8',first:'Layla',last:'Verna',short:'Layla V.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_9',first:'Maksym',last:'Marushchak',short:'Maksym M.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_10',first:'Melina',last:'Sahin',short:'Melina S.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_11',first:'Sira',last:'Wakal',short:'Sira W.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_hellgelb_12',first:'Violeta',last:'Ornicane',short:'Violeta O.',className:'6c',year:6,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:'Ribanna Tsehaye'},
  {id:'p6_dunkelgelb_1',first:'Andreas Ion',last:'Tudor',short:'Andreas Ion T.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_2',first:'Emilia',last:'Ley',short:'Emilia L.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_3',first:'Ihor',last:'Boichenko',short:'Ihor B.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_4',first:'Jedida',last:'Autenrieth',short:'Jedida A.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_5',first:'Jolina',last:'Butsch',short:'Jolina B.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_6',first:'Julien',last:'Stelzer',short:'Julien S.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_7',first:'Lukas',last:'Gazso',short:'Lukas G.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_8',first:'Samuel',last:'Kneißl',short:'Samuel K.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_9',first:'Sarah',last:'Golz',short:'Sarah G.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_10',first:'Sophia',last:'Kugler',short:'Sophia K.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_11',first:'Sophia-Loren',last:'Glasbrenner',short:'Sophia-Loren G.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_dunkelgelb_12',first:'Till',last:'Grambow',short:'Till G.',className:'6c',year:6,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:'Julia Bachmair'},
  {id:'p6_lila_1',first:'Anne',last:'Breit',short:'Anne B.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_2',first:'Arik',last:'Witowski',short:'Arik W.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_3',first:'Emil',last:'Franz',short:'Emil F.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_4',first:'Felia',last:'Harbich',short:'Felia H.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_5',first:'Layth',last:'Dawood',short:'Layth D.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_6',first:'Leonita',last:'Krasniqi',short:'Leonita K.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_7',first:'Lio',last:'Ebert',short:'Lio E.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_8',first:'Nick',last:'Kochendörfer',short:'Nick K.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_9',first:'Ole',last:'Franz',short:'Ole F.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_10',first:'Rabija',last:'Aerovic',short:'Rabija A.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_11',first:'Ritaq',last:'Aldarweesh',short:'Ritaq A.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_12',first:'Sita',last:'Held',short:'Sita H.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_lila_13',first:'Teodora',last:'Aerovic',short:'Teodora A.',className:'6d',year:6,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:'Peter Brusda-Gleichmann'},
  {id:'p6_pink_1',first:'Alina',last:'Oechsler',short:'Alina O.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_2',first:'Asma',last:'Alshlash',short:'Asma A.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_3',first:'David',last:'Navaratnam',short:'David N.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_4',first:'Frank',last:'Schöne',short:'Frank S.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_5',first:'Helena',last:'Straka',short:'Helena S.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_6',first:'Ida',last:'Wolbert',short:'Ida W.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_7',first:'Lennard',last:'Sommer',short:'Lennard S.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_8',first:'Liam',last:'Wieland',short:'Liam W.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_9',first:'Lotta',last:'Woitke',short:'Lotta W.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_10',first:'Mark',last:'Turianskyi',short:'Mark T.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_11',first:'Maya Sophie',last:'Schröder',short:'Maya Sophie S.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_pink_12',first:'Semih',last:'Krasniqi',short:'Semih K.',className:'6d',year:6,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:'Juliane Schöne'},
  {id:'p6_hellgrun_1',first:'Amar',last:'Shillova',short:'Amar S.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_2',first:'Amelie',last:'Bussmann',short:'Amelie B.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_3',first:'Amelie',last:'Deeg',short:'Amelie D.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_4',first:'Elif',last:'Pazarcikli',short:'Elif P.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_5',first:'Emma-Lina',last:'Götz',short:'Emma-Lina G.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_6',first:'Jamie',last:'Omooloye',short:'Jamie O.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_7',first:'Lewin',last:'Rutsch',short:'Lewin R.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_8',first:'Marie',last:'Nagel',short:'Marie N.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_9',first:'Mika',last:'Kläßing',short:'Mika K.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_10',first:'Mila',last:'Korb',short:'Mila K.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_hellgrun_11',first:'Pia',last:'Poggensee',short:'Pia P.',className:'6e',year:6,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:'Melanie Schnepf'},
  {id:'p6_dunkelgrun_1',first:'Ela',last:'Koyugül',short:'Ela K.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_2',first:'Elias',last:'Podstawek',short:'Elias P.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_3',first:'Emma',last:'Fritz',short:'Emma F.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_4',first:'Felix-Joel',last:'Gerull',short:'Felix-Joel G.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_5',first:'Georgij',last:'Root',short:'Georgij R.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_6',first:'Helena',last:'Bilk',short:'Helena B.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_7',first:'Helena',last:'Dyba',short:'Helena D.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_8',first:'Hlib',last:'Ovseichuk',short:'Hlib O.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_9',first:'Matvii',last:'Anufriiev',short:'Matvii A.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_10',first:'Max',last:'Schlenker',short:'Max S.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_11',first:'Mira-Sofie',last:'Eckenweber',short:'Mira-Sofie E.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p6_dunkelgrun_12',first:'Raphael',last:'Moser',short:'Raphael M.',className:'6e',year:6,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:'Jörg Vogt'},
  {id:'p7_hellblau_1',first:'Aaish',last:'Ananthiran',short:'Aaish A.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_2',first:'Arina',last:'Yogarajah',short:'Arina Y.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_3',first:'Asaad',last:'Abdulrahem',short:'Asaad A.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_4',first:'Eflin',last:'Göksu',short:'Eflin G.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_5',first:'Fabian',last:'Seeger',short:'Fabian S.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_6',first:'Klara',last:'Zimmermann',short:'Klara Z.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_7',first:'Levi',last:'Bay',short:'Levi B.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_8',first:'Luca',last:'Tarne',short:'Luca T.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_9',first:'Nils',last:'Hettenbach',short:'Nils H.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_10',first:'Parisa',last:'Hosseini',short:'Parisa H.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_11',first:'Rosalie',last:'Wieland',short:'Rosalie W.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellblau_12',first:'Yunus',last:'Arslan',short:'Yunus A.',className:'7a',year:7,team:'Blau',coachingGroup:'Hellblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_1',first:'Ainaz',last:'Ahmadi',short:'Ainaz A.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_2',first:'Alishba',last:'Merkle',short:'Alishba M.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_3',first:'Alissa',last:'Gräter',short:'Alissa G.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_4',first:'Felice',last:'Schulz',short:'Felice S.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_5',first:'Felix',last:'Can',short:'Felix C.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_6',first:'Gabriel',last:'Haag',short:'Gabriel H.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_7',first:'Jan',last:'Hain',short:'Jan H.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_8',first:'Jeyjee',last:'Herbst',short:'Jeyjee H.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_9',first:'Luca',last:'Regner',short:'Luca R.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_10',first:'Melani',last:'Perko',short:'Melani P.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_dunkelblau_11',first:'Sena',last:'Bayraktar',short:'Sena B.',className:'7a',year:7,team:'Blau',coachingGroup:'Dunkelblau',color:teamColor('Blau'),coach:''},
  {id:'p7_hellrot_1',first:'Almira',last:'Erdogan',short:'Almira E.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_2',first:'Anna',last:'Röger',short:'Anna R.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_3',first:'Ecem',last:'Celik',short:'Ecem C.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_4',first:'Ema',last:'Zalac',short:'Ema Z.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_5',first:'Lieselotte-Maite',last:'Grimm',short:'Lieselotte-Maite G.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_6',first:'Lotta',last:'Thurner',short:'Lotta T.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_7',first:'Madeleine',last:'Martens',short:'Madeleine M.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_8',first:'Mia',last:'Grauer',short:'Mia G.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_9',first:'Toni',last:'Stark',short:'Toni S.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_10',first:'Viktoria',last:'Hitsevych',short:'Viktoria H.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellrot_11',first:'Zano',last:'Ahmed',short:'Zano A.',className:'7b',year:7,team:'Rot',coachingGroup:'Hellrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_1',first:'Anastasia',last:'Perepech',short:'Anastasia P.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_2',first:'Annie',last:'Siegle',short:'Annie S.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_3',first:'Danil',last:'Kolomnikov',short:'Danil K.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_4',first:'David',last:'Munk',short:'David M.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_5',first:'Elissar',last:'Estef',short:'Elissar E.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_6',first:'Giulio',last:'Meffert',short:'Giulio M.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_7',first:'Heorhii',last:'Startsev',short:'Heorhii S.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_8',first:'Isil',last:'Mamin',short:'Isil M.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_9',first:'Lika',last:'Adejkin',short:'Lika A.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_10',first:'Lina',last:'Kübler',short:'Lina K.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_11',first:'Louis',last:'Kuttruff',short:'Louis K.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_12',first:'Mariam',last:'Khutsaria',short:'Mariam K.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_dunkelrot_13',first:'Ramadane',last:'Aboulaye',short:'Ramadane A.',className:'7b',year:7,team:'Rot',coachingGroup:'Dunkelrot',color:teamColor('Rot'),coach:''},
  {id:'p7_hellgelb_1',first:'Abdul',last:'Shayman',short:'Abdul S.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_2',first:'Anton',last:'Stetsiura',short:'Anton S.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_3',first:'Joleen',last:'Preuß',short:'Joleen P.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_4',first:'Leon-Koray',last:'Moser',short:'Leon-Koray M.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_5',first:'Max',last:'Andruschkewitsch',short:'Max A.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_6',first:'Niklas',last:'Anzimiroff',short:'Niklas A.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_7',first:'Paul',last:'Ackermann',short:'Paul A.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_8',first:'Sophia',last:'Straka',short:'Sophia S.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_9',first:'Tabasom',last:'Azimi',short:'Tabasom A.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_10',first:'Umut',last:'Ozkaya',short:'Umut O.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_hellgelb_11',first:'Vladut',last:'Zamfirescu',short:'Vladut Z.',className:'7c',year:7,team:'Gelb',coachingGroup:'Hellgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_1',first:'Aylin',last:'Yildirim',short:'Aylin Y.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_2',first:'Ben',last:'Meyer',short:'Ben M.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_3',first:'David',last:'Rehrauer',short:'David R.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_4',first:'Felix',last:'Kroll',short:'Felix K.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_5',first:'Frini',last:'Roll',short:'Frini R.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_6',first:'Gisèle',last:'Novotny',short:'Gisèle N.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_7',first:'Jannik',last:'Thier',short:'Jannik T.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_8',first:'Jona',last:'Bezelberger',short:'Jona B.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_9',first:'Leonie',last:'Leipersberger',short:'Leonie L.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_10',first:'Luca',last:'Stöcker',short:'Luca S.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_11',first:'Mary Idada',last:'Omkha',short:'Mary Idada O.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_12',first:'Miguel',last:'Grünberg',short:'Miguel G.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_dunkelgelb_13',first:'Mika',last:'Stanczak',short:'Mika S.',className:'7c',year:7,team:'Gelb',coachingGroup:'Dunkelgelb',color:teamColor('Gelb'),coach:''},
  {id:'p7_lila_1',first:'Alisija',last:'Weizel',short:'Alisija W.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_2',first:'Jood',last:'Saban',short:'Jood S.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_3',first:'Katerina',last:'Archipenko',short:'Katerina A.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_4',first:'Kira',last:'Kochura',short:'Kira K.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_5',first:'Lana',last:'Korb',short:'Lana K.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_6',first:'Luan',last:'Skaritzky',short:'Luan S.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_7',first:'Mara',last:'Tasgöz',short:'Mara T.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_8',first:'Mariam Fakkas',last:'Albayed',short:'Mariam Fakkas A.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_9',first:'Marietta',last:'Graf',short:'Marietta G.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_10',first:'Max',last:'Schüler',short:'Max S.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_11',first:'Morik',last:'Schad',short:'Morik S.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_12',first:'Nala',last:'Aydemir',short:'Nala A.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_13',first:'Ramona',last:'Hieber',short:'Ramona H.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_lila_14',first:'Zahra',last:'Alhamad',short:'Zahra A.',className:'7d',year:7,team:'Violett',coachingGroup:'Lila',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_1',first:'Amelie',last:'Pfizenmaier',short:'Amelie P.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_2',first:'Andrei',last:'Constantin',short:'Andrei C.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_3',first:'Emilia',last:'Plieger',short:'Emilia P.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_4',first:'Finn',last:'Fritz',short:'Finn F.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_5',first:'Ian',last:'Lenz',short:'Ian L.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_6',first:'Jonas',last:'Stünkel',short:'Jonas S.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_7',first:'Lauresa',last:'Tairi',short:'Lauresa T.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_8',first:'Leon',last:'Domnowski',short:'Leon D.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_9',first:'Naomi',last:'Eiwen',short:'Naomi E.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_10',first:'Panisa',last:'Semiari',short:'Panisa S.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_11',first:'Sophia',last:'Papio',short:'Sophia P.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_12',first:'Tom',last:'Hettenbach',short:'Tom H.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_pink_13',first:'Zoey',last:'Behr',short:'Zoey B.',className:'7d',year:7,team:'Violett',coachingGroup:'Pink',color:teamColor('Violett'),coach:''},
  {id:'p7_hellgrun_1',first:'Ben',last:'Zimmermann',short:'Ben Z.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_2',first:'Bryan',last:'Wanda Tchuisseu',short:'Bryan W.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_3',first:'Eriselda',last:'Plaku',short:'Eriselda P.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_4',first:'Erva',last:'Vural',short:'Erva V.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_5',first:'Ida',last:'Taubald',short:'Ida T.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_6',first:'Kimberly',last:'Pisano',short:'Kimberly P.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_7',first:'Mathilda',last:'Poser',short:'Mathilda P.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_8',first:'Salim',last:'Pochanke',short:'Salim P.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_9',first:'Sofiia',last:'Semak',short:'Sofiia S.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_10',first:'Stefan',last:'Jovicic',short:'Stefan J.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_hellgrun_11',first:'Suela',last:'Kameraj',short:'Suela K.',className:'7e',year:7,team:'Grün',coachingGroup:'Hellgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_1',first:'Adelin',last:'Ivan',short:'Adelin I.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_2',first:'Ela',last:'Kamay',short:'Ela K.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_3',first:'Emma',last:'Leyrer',short:'Emma L.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_4',first:'Erilda',last:'Plaku',short:'Erilda P.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_5',first:'Ida',last:'Groh',short:'Ida G.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_6',first:'Iwan',last:'Shumkin',short:'Iwan S.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_7',first:'Marco',last:'Böhm',short:'Marco B.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_8',first:'Mila',last:'Dambach',short:'Mila D.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_9',first:'Moritz',last:'Schibalski',short:'Moritz S.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_10',first:'Piero',last:'Di Candia',short:'Piero D.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_11',first:'Sadete',last:'Zekaj',short:'Sadete Z.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_12',first:'Sarah',last:'Häußler',short:'Sarah H.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
  {id:'p7_dunkelgrun_13',first:'Taylor',last:'Dohm',short:'Taylor D.',className:'7e',year:7,team:'Grün',coachingGroup:'Dunkelgrün',color:teamColor('Grün'),coach:''},
 ],
 competencies:[...english5Competencies(),
 {id:'w_school_geo',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'GeoLab',subject:'Geographie',category:'Orientierung',area:'Orientierung',level:'G/M/E',text:'Ich kann Lagepläne und Karten nutzen, um mich sicher zu orientieren.',includeInLeb:true,order:10,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_media',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'MediaLab',subject:'Informatik & Medienbildung',category:'Digitale Werkzeuge',area:'Digitale Werkzeuge',level:'G/M/E',text:'Ich kann digitale Werkzeuge zur Recherche, Dokumentation und Präsentation verantwortungsvoll nutzen.',includeInLeb:true,order:20,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_history',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'HistoryLab',subject:'Geschichte',category:'Quellen',area:'Quellen',level:'G/M/E',text:'Ich kann Informationen aus einfachen historischen Quellen gewinnen und dokumentieren.',includeInLeb:true,order:30,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_art',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'Bildende Kunst',subject:'Bildende Kunst',category:'Gestaltung',area:'Gestaltung',level:'G/M/E',text:'Ich kann Informationen übersichtlich visualisieren und Lernprodukte adressatengerecht gestalten.',includeInLeb:true,order:40,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''},
 {id:'w_school_music',type:'workshop',year:5,sprint:1,projectId:'project_school',phase:'base',lab:'Musik',subject:'Musik',category:'Präsentation',area:'Präsentation',level:'G/M/E',text:'Ich kann musikalische oder auditive Elemente für eine gemeinsame Präsentation gestalten.',includeInLeb:true,order:50,maxPoints:null,scoreConfig:{...DEFAULT_SCORE_CONFIG},note:''}
 ]
};