let lebMode='fach';
let lebSubject='Englisch';
let lebSelectedPupil=null;
function leb(){ const subjects=[...CORE_SUBJECTS,...Store.subjects]; if(!subjects.includes(lebSubject))lebSubject=subjects[0]; let content=header('Lernentwicklungsberichte','Fachtexte erzeugen, bearbeiten, speichern und kopieren.'); content+=`<div class="toolbar"><button class="chip ${lebMode==='fach'?'dark':''}" onclick="lebMode='fach';render()">Fachansicht</button><button class="chip ${lebMode==='schueler'?'dark':''}" onclick="lebMode='schueler';render()">Schüleransicht</button></div>`; content+=lebMode==='fach'?renderLebSubjectView(subjects):renderLebStudentView(); shell(content); }
function renderLebSubjectView(subjects){ const pupils=Store.pupils.filter(p=>String(p.className).startsWith(String(State.year))).sort((a,b)=>a.last.localeCompare(b.last,'de')||a.first.localeCompare(b.first,'de')); if(!lebSelectedPupil&&pupils[0])lebSelectedPupil=pupils[0].id; const selected=pupils.find(p=>p.id===lebSelectedPupil)||pupils[0]; return `<div class="toolbar formgrid"><div><label>Jahrgang</label><select onchange="State.year=Number(this.value);lebSelectedPupil=null;render()">${[5,6,7].map(y=>`<option value="${y}" ${State.year===y?'selected':''}>Jahrgang ${y}</option>`).join('')}</select></div><div><label>Fach</label><select onchange="lebSubject=this.value;lebSelectedPupil=null;render()">${subjects.map(s=>`<option ${lebSubject===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div></div><div class="grid2"><div class="card"><h2>${esc(lebSubject)}</h2><p>${subjectDoneCount(pupils,lebSubject)} von ${pupils.length} Texten gespeichert.</p><div class="studentCards compact">${pupils.map(p=>`<div class="studentCard ${selected&&selected.id===p.id?'selectedCard':''}"><div><b>${esc(p.short)}</b><div class="mini">${p.className} · ${lebSubjectStatus(p,lebSubject)}</div></div><button class="chip" onclick="lebSelectedPupil='${p.id}';render()">Öffnen</button></div>`).join('')}</div></div><div class="card">${selected?renderSubjectEditor(selected,lebSubject,pupils):'Keine Schüler*innen vorhanden.'}</div></div>`; }
function renderSubjectEditor(pupil,subject,pupils){ const key=lebSubjectKey(pupil.id,subject); const generated=generateSubjectOnlyText(pupil,subject); const saved=Store.lebDrafts[key]||generated; const idx=pupils.findIndex(p=>p.id===pupil.id); return `<h2>${esc(pupil.short)} · ${esc(subject)}</h2><textarea id="subjectLebText" class="bigText">${esc(saved)}</textarea><button class="chip dark" onclick="saveSubjectLeb('${pupil.id}','${esc(subject)}')">Speichern</button><button class="chip dark" onclick="saveSubjectLebAndNext('${pupil.id}','${esc(subject)}')">Speichern & weiter</button><button class="chip" onclick="document.getElementById('subjectLebText').value=generateSubjectOnlyText(Store.pupils.find(p=>p.id==='${pupil.id}'),'${esc(subject)}')">neu erzeugen</button><button class="chip" onclick="copySubjectLeb()">kopieren</button><div class="section">Navigation</div><button class="chip" ${idx<=0?'disabled':''} onclick="lebSelectedPupil='${pupils[Math.max(0,idx-1)]?.id}';render()">← vorherig</button><button class="chip" ${idx>=pupils.length-1?'disabled':''} onclick="lebSelectedPupil='${pupils[Math.min(pupils.length-1,idx+1)]?.id}';render()">weiter →</button>`; }
function subjectDoneCount(pupils,subject){return pupils.filter(p=>Store.lebDrafts[lebSubjectKey(p.id,subject)]).length;}
function lebSubjectKey(pupilId,subject){return 'subjectLeb_'+pupilId+'_'+subject;}
function lebSubjectStatus(pupil,subject){ if(Store.lebDrafts[lebSubjectKey(pupil.id,subject)])return'<span class="statusPill status-green">fertig</span>'; const rows=getRowsForPupil(pupil).filter(r=>r.comp.subject===subject); return rows.length?'<span class="statusPill status-yellow">Entwurf</span>':'<span class="statusPill status-empty">fehlt</span>'; }
function saveSubjectLeb(pupilId,subject){Store.lebDrafts[lebSubjectKey(pupilId,subject)]=document.getElementById('subjectLebText').value;Store.save();toast();render();}
function saveSubjectLebAndNext(pupilId,subject){Store.lebDrafts[lebSubjectKey(pupilId,subject)]=document.getElementById('subjectLebText').value;Store.save(); const pupils=Store.pupils.filter(p=>String(p.className).startsWith(String(State.year))).sort((a,b)=>a.last.localeCompare(b.last,'de')||a.first.localeCompare(b.first,'de')); const idx=pupils.findIndex(p=>p.id===pupilId); if(idx<pupils.length-1)lebSelectedPupil=pupils[idx+1].id; toast(); render();}
function copySubjectLeb(){navigator.clipboard.writeText(document.getElementById('subjectLebText').value);toast('Kopiert');}
function renderLebStudentView(){ const pupils=Store.pupils.filter(p=>String(p.className).startsWith(String(State.year))).sort((a,b)=>a.last.localeCompare(b.last,'de')||a.first.localeCompare(b.first,'de')); if(!State.pupil&&pupils[0])State.pupil=pupils[0].id; const pupil=Store.pupils.find(p=>p.id===State.pupil)||pupils[0]; if(!pupil)return'<div class="card">Keine Schüler*innen vorhanden.</div>'; const text=generateFullLebText(pupil); return `<div class="toolbar"><label>Schüler*in</label><select onchange="State.pupil=this.value;render()">${pupils.map(p=>`<option value="${p.id}" ${pupil.id===p.id?'selected':''}>${esc(p.short)} · ${esc(p.team)}</option>`).join('')}</select></div><div class="card"><h2>${esc(pupil.short)}</h2><textarea id="fullLebText" class="bigText">${esc(Store.lebDrafts[pupil.id]||text)}</textarea><button class="chip dark" onclick="Store.lebDrafts['${pupil.id}']=document.getElementById('fullLebText').value;Store.save();toast();">Speichern</button><button class="chip" onclick="document.getElementById('fullLebText').value=generateFullLebText(Store.pupils.find(p=>p.id==='${pupil.id}'))">neu erzeugen</button><button class="chip" onclick="navigator.clipboard.writeText(document.getElementById('fullLebText').value);toast('Kopiert')">kopieren</button></div>`; }
function getRowsForPupil(pupil){return Object.entries(Store.records).filter(([key])=>key.endsWith('|'+pupil.id)).map(([key,record])=>{const comp=Store.competencies.find(c=>c.id===key.split('|')[0]);return comp&&comp.includeInLeb?{comp,record}:null;}).filter(Boolean);}
function generateSubjectOnlyText(pupil,subject){ const rows=getRowsForPupil(pupil).filter(r=>r.comp.subject===subject); if(!rows.length)return`Für ${pupil.first} liegen im Fach ${subject} noch keine dokumentierten Kompetenzen vor.`; return generateSubjectParagraph(pupil,subject,rows);}
function generateFullLebText(pupil){ const rows=getRowsForPupil(pupil); if(!rows.length)return`${pupil.first} hat bisher noch keine dokumentierten Kompetenzbewertungen erhalten.`; const by={}; rows.forEach(r=>{by[r.comp.subject]=by[r.comp.subject]||[];by[r.comp.subject].push(r);}); let text=Object.entries(by).map(([subject,items])=>generateSubjectParagraph(pupil,subject,items)).join('\n\n'); const behaviourText=generateBehaviourParagraph(pupil); const activityText=generateActivityParagraph(pupil); return [text,behaviourText,activityText].filter(Boolean).join('\n\n'); }
function generateSubjectParagraph(pupil,subject,items){ const green=items.filter(r=>r.record.current==='green'), yellow=items.filter(r=>r.record.current==='yellow'), red=items.filter(r=>r.record.current==='red'); const level=mostCommon(items.map(r=>r.record.level).filter(Boolean))||'dem gewählten'; let text=`${pupil.first} arbeitet im Fach ${subject} überwiegend auf ${level}-Niveau. `; if(green.length)text+=`${pupil.first} zeigt Sicherheit in ${listAreas(green)}. `; if(yellow.length)text+=`In ${listAreas(yellow)} gelingen die Anforderungen bereits teilweise; hier entwickelt ${pupil.first} zunehmend mehr Sicherheit. `; if(red.length)text+=`Bei ${listAreas(red)} benötigt ${pupil.first} noch klare Unterstützung und weitere Übung. `; const scores=items.filter(r=>r.record.score).slice(-2); if(scores.length)text+=`Die dokumentierten Punkteergebnisse (${scores.map(r=>r.record.score.points+'/'+r.record.score.max+' Punkte').join(', ')}) stützen diese Einschätzung. `; return text.trim();}
function listAreas(rows){return [...new Set(rows.slice(0,3).map(r=>cleanCompetencyText(r.comp.text)))].join('; ');}
function cleanCompetencyText(text){return String(text||'').replace(/^Ich kann\s+/i,'').replace(/^I can\s+/i,'').replace(/\.$/,'');}
function mostCommon(arr){ if(!arr.length)return null; const c={}; arr.forEach(x=>c[x]=(c[x]||0)+1); return Object.entries(c).sort((a,b)=>b[1]-a[1])[0][0];}

function generateBehaviourParagraph(pupil){ const b=Store.behaviour[pupil.id]; if(!b)return''; const labels=Object.fromEntries(BEHAVIOUR_FIELDS); const strengths=Object.entries(b.ratings||{}).filter(([,v])=>v==='meist sicher'||v==='besonders ausgeprägt').map(([k])=>labels[k]); const development=Object.entries(b.ratings||{}).filter(([,v])=>v==='braucht Begleitung'||v==='teilweise selbstständig').map(([k])=>labels[k]); let text=''; if(strengths.length)text+=`${pupil.first} zeigte im Lernatelier besonders in den Bereichen ${strengths.slice(0,3).join(', ')} eine positive Entwicklung. `; if(development.length)text+=`Weiterarbeiten sollte ${pupil.first} vor allem an ${development.slice(0,2).join(' und ')}. `; if(Number(b.teamStars)>=3)text+='Drei vollständig erreichte TeamStar-Karten unterstreichen das sehr positive Arbeits- und Sozialverhalten. '; else if(Number(b.teamStars)>=1)text+=`Die ${b.teamStars===1?'erreichte TeamStar-Karte':b.teamStars+' erreichten TeamStar-Karten'} zeigen eine insgesamt positive Entwicklung. `; if(b.note)text+=b.note.trim(); return text.trim(); }
function generateActivityParagraph(pupil){ const rows=pupilActivities(pupil.id).filter(x=>x.activity.lebEnabled!==false); if(!rows.length)return''; const parts=rows.map(({activity,record})=>{let s=activity.name; if(record.engagement)s+=` (${record.engagement})`; return s;}); return `${pupil.first} nahm darüber hinaus an ${parts.join(' und ')} teil.`; }
