let lebSectionsState = {};
function leb(){
  const list=Store.pupils.slice().sort((a,b)=>a.last.localeCompare(b.last,'de')||a.first.localeCompare(b.first,'de'));
  if(!State.pupil) State.pupil=list[0]?.id; const pupil=Store.pupils.find(p=>p.id===State.pupil); const sections=buildLebSections(pupil);
  if(!lebSectionsState[pupil.id]){ lebSectionsState[pupil.id]={}; sections.forEach(s=>lebSectionsState[pupil.id][s.id]={include:true,text:s.text}); }
  let content=header('Lernentwicklungsberichte','LEB-Assistent mit auswählbaren und bearbeitbaren Abschnitten.');
  content += `<div class="toolbar"><label>Schüler*in</label><select onchange="State.pupil=this.value;render()">${list.map(p=>`<option value="${p.id}" ${State.pupil===p.id?'selected':''}>${p.short} (${p.team}) · Coach ${p.coach}</option>`).join('')}</select></div>`;
  content += `<div class="grid2"><div class="card"><h2>${pupil.short} (${pupil.team})</h2><p>Coach ${pupil.coach} · ${pupil.className}</p><div class="section">Abschnitte</div>${sections.map(s=>renderLebSection(s,pupil)).join('')}<div class="section">Eigene Ergänzung</div><textarea id="ownLebAddition" oninput="updateLebPreview()" placeholder="Optionaler eigener Abschnitt...">${Store.lebDrafts[pupil.id+'_addition'] || ''}</textarea><button class="chip dark" onclick="saveLebAssistant()">LEB speichern</button><button class="chip" onclick="copyLebPreview()">Text kopieren</button></div><div class="card"><h2>Vorschau</h2><div id="lebPreview" class="lebText">${composeLebPreview(pupil,sections)}</div></div></div>`;
  shell(content);
}
function renderLebSection(section,pupil){ const state=lebSectionsState[pupil.id]?.[section.id]||{include:true,text:section.text}; return `<div class="card" style="box-shadow:none;margin-bottom:12px"><label><input type="checkbox" ${state.include?'checked':''} onchange="setLebSectionInclude('${pupil.id}','${section.id}',this.checked)"> ${section.title}</label><textarea oninput="setLebSectionText('${pupil.id}','${section.id}',this.value)" style="min-height:120px">${state.text}</textarea></div>`; }
function setLebSectionInclude(pid,sid,val){lebSectionsState[pid][sid].include=val;updateLebPreview();}
function setLebSectionText(pid,sid,val){lebSectionsState[pid][sid].text=val;updateLebPreview();}
function updateLebPreview(){const pupil=Store.pupils.find(p=>p.id===State.pupil); const preview=document.getElementById('lebPreview'); if(preview) preview.textContent=composeLebPreview(pupil,buildLebSections(pupil));}
function composeLebPreview(pupil,sections){const state=lebSectionsState[pupil.id]||{}; const parts=sections.filter(s=>state[s.id]?.include).map(s=>state[s.id]?.text||s.text).filter(Boolean); const addition=document.getElementById('ownLebAddition')?.value||Store.lebDrafts[pupil.id+'_addition']||''; if(addition.trim())parts.push(addition.trim()); return parts.join('\n\n');}
function saveLebAssistant(){const pupil=Store.pupils.find(p=>p.id===State.pupil); Store.lebDrafts[pupil.id]=composeLebPreview(pupil,buildLebSections(pupil)); Store.lebDrafts[pupil.id+'_addition']=document.getElementById('ownLebAddition')?.value||''; Store.save(); toast();}
function copyLebPreview(){navigator.clipboard.writeText(document.getElementById('lebPreview').textContent); toast('Kopiert');}
function buildLebSections(pupil){
 const rows=Object.entries(Store.records).filter(([k])=>k.endsWith('|'+pupil.id)).map(([k,record])=>{const comp=Store.competencies.find(c=>c.id===k.split('|')[0]); return comp&&comp.includeInLeb?{comp,record}:null;}).filter(Boolean);
 if(!rows.length)return[{id:'empty',title:'Hinweis',text:`${pupil.first} hat im Werkstattunterricht noch keine dokumentierten Kompetenzbewertungen erhalten.`}];
 const sections=[]; const process=rows.filter(r=>r.comp.kind==='prozess'); const fach=rows.filter(r=>r.comp.kind==='fach'); const ptxt=generateProcessParagraph(pupil,process); if(ptxt)sections.push({id:'process',title:'Arbeits- und Lernverhalten',text:ptxt});
 const by={}; fach.forEach(r=>{by[r.comp.subject]=by[r.comp.subject]||[];by[r.comp.subject].push(r);}); Object.entries(by).forEach(([sub,items])=>sections.push({id:'subject_'+sub.replace(/\W/g,'_'),title:sub,text:generateSubjectParagraph(pupil,sub,items)}));
 const notes=rows.flatMap(r=>(r.record.notes||[]).map(n=>n.note)).filter(Boolean).slice(-3); if(notes.length)sections.push({id:'notes',title:'Besondere Beobachtungen',text:`Besonders festgehalten wurde: ${notes.join(' ')}`}); const next=generateNextSteps(pupil,rows); if(next)sections.push({id:'next',title:'Nächste Entwicklungsschritte',text:next}); return sections;
}
function generateProcessParagraph(pupil,rows){if(!rows.length)return''; const g=rows.filter(r=>r.record.current==='green'), y=rows.filter(r=>r.record.current==='yellow'), red=rows.filter(r=>r.record.current==='red'); const parts=[]; if(g.length)parts.push(`${pupil.first} zeigt im Bereich ${g.slice(0,2).map(r=>r.comp.area.toLowerCase()).join(' und ')} ein sicheres Arbeitsverhalten.`); if(y.length)parts.push(`In ${y.slice(0,2).map(r=>r.comp.area.toLowerCase()).join(' und ')} entwickelt ${pupil.first} zunehmend Sicherheit.`); if(red.length)parts.push(`Im Bereich ${red.slice(0,1).map(r=>r.comp.area.toLowerCase()).join(' und ')} benötigt ${pupil.first} noch Unterstützung.`); return parts.join(' ');}
function generateSubjectParagraph(pupil,subject,items){const levels=items.map(r=>r.record.level).filter(Boolean); const level=mostCommon(levels)||'dem gewählten'; const g=items.filter(r=>r.record.current==='green'), y=items.filter(r=>r.record.current==='yellow'), red=items.filter(r=>r.record.current==='red'); let text=`Im Fach ${subject} arbeitet ${pupil.first} überwiegend auf ${level}-Niveau. `; if(g.length)text+=`${pupil.first} kann zentrale Anforderungen sicher bearbeiten. `; if(y.length)text+=`In einzelnen Bereichen zeigt ${pupil.first} bereits sichere Ansätze und entwickelt zunehmend Sicherheit. `; if(red.length)text+=`Bei einzelnen Anforderungen benötigt ${pupil.first} noch Unterstützung. `; if(hasProgress(items))text+=`Im Verlauf der Werkstattarbeit ist eine positive Entwicklung erkennbar.`; return text.trim();}
function generateNextSteps(pupil,rows){const needs=rows.filter(r=>r.record.current==='yellow'||r.record.current==='red').slice(0,2); if(!needs.length)return''; return `${pupil.first} sollte weiter daran arbeiten, in den Bereichen ${needs.map(r=>r.comp.area.toLowerCase()).join(' und ')} sicherer zu werden.`;}
function hasProgress(items){return items.some(r=>{const h=r.record.history||[]; if(h.length<2)return false; const rank={red:0,yellow:1,green:2}; return rank[h[h.length-1].value]>rank[h[0].value];});}
function mostCommon(arr){if(!arr.length)return null; const counts={}; arr.forEach(x=>counts[x]=(counts[x]||0)+1); return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];}
