const State = {view:'dashboard',role:'Stufenleitung',teacher:'Juliane',year:5,sprint:2,subject:'Geographie',competency:null,search:'',team:'alle',level:'alle',pupil:null,dialog:null,studentScope:'all'};
function today(){ return new Date().toLocaleDateString('de-DE'); }
function canEdit(){ return State.role==='Stufenleitung'||State.role==='Admin'; }
function recKey(competencyId,pupilId){ return competencyId+'|'+pupilId; }
function sprintObj(n=State.sprint){ return Store.sprints.find(s=>s.year===State.year && s.number===Number(n)); }
function sprintName(n){ return sprintObj(n)?.name || ('Sprint '+n); }
function esc(v){ return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); }
function setView(view){ State.view=view; State.dialog=null; State.pupil=null; render(); }
function toast(msg='Gespeichert'){ const t=document.createElement('div'); t.className='toast show'; t.textContent=msg; document.body.appendChild(t); setTimeout(()=>t.remove(),1100); }
function header(title,hint){ return `<div class="pageHead"><div><h1>${title}</h1><div class="hint">${hint||''}</div></div></div>`; }
function navButton(view,label,icon){ if(view==='admin'&&!canEdit())return''; return `<button class="${State.view===view?'active':''}" onclick="setView('${view}')"><span>${icon}</span>${label}</button>`; }
function shell(content){ document.getElementById('app').innerHTML=`<div class="app"><aside><div class="brand">KOMPASS</div><div class="sub">Version 4.2 · offline</div><div class="userbox"><label>Rolle</label><select onchange="State.role=this.value;render()"><option ${State.role==='Lehrkraft'?'selected':''}>Lehrkraft</option><option ${State.role==='Stufenleitung'?'selected':''}>Stufenleitung</option><option ${State.role==='Admin'?'selected':''}>Admin</option></select><label>Lehrkraft</label><input value="${esc(State.teacher)}" onchange="State.teacher=this.value;render()"></div><div class="nav">${navButton('dashboard','Dashboard','⌂')}${navButton('students','Schülerinnen & Schüler','◌')}${navButton('workshop','Werkstattunterricht','▦')}${navButton('core','Kernfächer','◎')}${navButton('activities','Angebote','✦')}${navButton('behaviour','Arbeits- & Sozialverhalten','★')}${navButton('leb','Lernentwicklungsberichte','✎')}${navButton('admin','Kompetenzverwaltung','☷')}${navButton('settings','Einstellungen','⚙')}</div></aside><main>${content}</main></div>`; renderDialog(); }
function statusLabel(value){ if(value==='green')return'<span class="statusPill status-green">erreicht</span>'; if(value==='yellow')return'<span class="statusPill status-yellow">teilweise erreicht</span>'; if(value==='red')return'<span class="statusPill status-red">noch nicht erreicht</span>'; return'<span class="statusPill status-empty">nicht bewertet</span>'; }
function statusPlain(value){ return value==='green'?'erreicht':value==='yellow'?'teilweise erreicht':value==='red'?'noch nicht erreicht':'nicht bewertet'; }
function scoreToStatus(percent, redMax, yellowMax){ if(percent<=redMax)return'red'; if(percent<=yellowMax)return'yellow'; return'green'; }
function teamColor(team){ return ({Blau:'blue',Rot:'rose',Gelb:'amber',Violett:'violet',Grün:'mint'}[team]||'blue'); }
function filteredPupils(){ return Store.pupils.filter(p=>String(p.className).startsWith(String(State.year))).filter(p=>State.team==='alle'||p.team===State.team).filter(p=>{const s=State.search.trim().toLowerCase(); return !s || (p.last+' '+p.first+' '+p.short).toLowerCase().includes(s);}).sort((a,b)=>a.last.localeCompare(b.last,'de')||a.first.localeCompare(b.first,'de')); }
function render(){ const views={dashboard,students,workshop,core:coreSubjects,activities,behaviour,leb,admin,settings}; (views[State.view]||dashboard)(); }
